#!/usr/bin/env php
<?php
error_reporting( E_ALL );
require_once( dirname( __FILE__ ) . '/defines.php' );
/*
 * This script backs up the current wikiversions dat file to the /backup directory.
 *
 * @return void
 */
function backupWikiversions() {
	$common = '/home/wikipedia/common';
	$datPath = MULTIVER_CDB_DIR_HOME . '/wikiversions.dat';

	# Backup old wikiversions.dat...
	$timestamp = date( 'c' ); // ISO 8601
	$backupPath = "$common/multiversion/backup/wikiversions-$timestamp.dat";
	if ( !copy( $datPath, $backupPath ) ) {
		die( "Unable to write wikiversions.dat backup file at `$backupPath`.\n" );
	}
	echo "Wrote wikiversions.dat backup file at `$backupPath`.\n";
}

backupWikiversions();
