#!/usr/bin/env php
<?php
error_reporting( E_ALL );
/*
 * Populate wikiversions.cdb file using all the items in wikiversions.dat
 *
 * @return void
 */
function refreshWikiversionsCDB() {
	$common = '/home/wikipedia/common';

	$path = "$common/wikiversions.dat";
	$verList = array_filter( explode( "\n", file_get_contents( $path ) ) );
	if ( !count( $verList ) ) {
		die( "Unable to read wikiversions.dat.\n" );
	}

	$tmpDBPath = "$common/wikiversions.cdb.tmp";
	$finalDBPath = "$common/wikiversions.cdb";

	# Build new database at temp location...
	$db = dba_open( $tmpDBPath, "n", "cdb_make" );
	if ( !$db ) {
		die( "Unable to create wikiversions.cdb.\n" );
	}
	foreach ( $verList as $row ) {
		list( $dbName, $version ) = explode( ' ', $row );
		dba_insert( $dbName, $version, $db );
	}
	dba_close( $db );

	# Sanity...
	if ( !file_exists( $tmpDBPath ) ) {
		die( "Unable to create wikiversions.cdb.tmp.\n" );
	}

	# Move to final location only when finished...
	@unlink( $finalDBPath );
	if ( !rename( $tmpDBPath, $finalDBPath ) ) {
		die( "Unable to create wikiversions.cdb.\n" );
	}
}

refreshWikiversionsCDB();
