#!/usr/bin/env php
<?php
error_reporting( E_ALL );
require_once( dirname( __FILE__ ) . '/defines.php' );
/*
 * This script switches all wikis running one version to another version.
 * It merely changes the wikiversions.dat and wikiversions.cdb files on /home,
 * so they will still need to be synced to push the upgrade/downgrade.
 *
 * The first argument is the old version, typically of the format "php-X.XX".
 * If "all" is given, then all wikis will be switched over.
 * The second argument is the new version, typically of the format "php-X.XX".
 *
 * @return void
 */
function switchAllMediaWikis() {
	global $argv;
	$common = '/home/wikipedia/common';

	$argsValid = false;
	if ( count( $argv ) >= 3 ) {
		$oldVersion = $argv[1]; // e.g. "php-X.XX"
		$newVersion = $argv[2]; // e.g. "php-X.XX"
		if ( preg_match( '/^php-(?:\d+\.\d+|trunk)(?:-\d)?$/', $newVersion ) ) {
			$argsValid = true;
		}
	}

	if ( !$argsValid ) {
		die( "Usage: switchAllMediaWikis php-X.XX php-X.XX\n" );
	}

	if ( !file_exists( "$common/$newVersion" ) ) {
		die( "The directory `$common/$newVersion` does not exist.\n" );
	}

	$datPath = MULTIVER_CDB_DIR_HOME . '/wikiversions.dat';
	$verList = array_filter( explode( "\n", file_get_contents( $datPath ) ) );
	if ( !count( $verList ) ) {
		die( "Unable to read wikiversions.dat.\n" );
	}

	$what = '/^(\w+) ' . preg_quote( $oldVersion ) . '( |$)/';
	$with = '$1 ' . $newVersion . '$2';

	$count = 0;
	$datList = "";
	foreach ( $verList as $row ) {
		$n = 0;
		$datList .= preg_replace( $what, $with, trim( $row ), -1, $n ) . "\n";
		$count += $n;
	}

	# Backup old wikiversions.dat...
	$retVal = 1;
	passthru( "cd $common/multiversion && ./backupWikiversions", $retVal );
	( $retVal == 0 ) or die( 1 );

	# Update wikiversions.dat...
	if ( !file_put_contents( $datPath, $datList, LOCK_EX ) ) {
		die( "Unable to write to wikiversions.dat.\n" );
	}
	echo "Updated wikiversions.dat.\n";

	# Rebuild wikiversions.cdb...
	$retVal = 1;
	passthru( "cd $common/multiversion && ./refreshWikiversionsCDB", $retVal );
	( $retVal == 0 ) or die( 1 );

	echo "Re-configured $count wiki(s) from $oldVersion to $newVersion.\n";
}

switchAllMediaWikis();
