#!/usr/bin/env php
<?php
/**
 * Create/update various symlinks used in production.
 *
 * docroot/bits/static-current links to the latest production branch, respectively.
 * This provides a stable URL to large static assets that are served by extensions
 * and which do not change frequently.
 *
 * php links to the current primary deployed version of MediaWiki.
 *
 * Usage: updateBranchPointers [OPTIONS]
 *
 * Options:
 *   --dry-run: Don't touch the file system; only show what would be done.
 *
 */
error_reporting( E_ALL );
require_once( __DIR__ . '/defines.php' );

function isMain() {
	return basename( __FILE__ ) === basename( $_SERVER['SCRIPT_FILENAME'] );
}

function updateBranchPointers( $dryRun = false ) {
	$branchDirs = glob( MULTIVER_COMMON_APACHE . '/php-*', GLOB_ONLYDIR );

	if ( !is_array( $branchDirs ) || count( $branchDirs ) < 1 ) {
		fwrite( STDERR, __FUNCTION__ . ': no deployment branch directories found in ' . MULTIVER_COMMON_APACHE . "\n" );
		exit( 1 );
	}

	// Order directories using version_compare.
	// The native sort is lexographical which gives the wrong result for
	// collections such as [1.23wmf9, 1.23wmf10].
	usort( $branchDirs, 'version_compare' );

	$branches = array( 'current' => array_pop( $branchDirs ) );

	updateSymlink( MULTIVER_COMMON_HOME . '/php', $branches['current'], $dryRun );

	foreach( $branches as $branch => $target ) {
		echo "Updating $branch branch pointer...\n";

		$parent = MULTIVER_COMMON_HOME . "/docroot/bits/static-$branch";

		if ( !$dryRun && !file_exists( $parent ) && !mkdir( $parent, 0775 ) ) {
			fwrite( STDERR, __FUNCTION__ . ": $parent does not exist and could not be created.\n" );
			exit( 1 );
		}

		foreach( array( 'skins', 'extensions', 'resources' ) as $child ) {
			$link = $parent . '/' . $child;
			$dest = $target . '/' . $child;
			updateSymlink( $link, $dest, $dryRun );
		}
		echo "\n";
	}
}

/**
 * @param string $link
 * @param string $dest
 * @param bool $dryRun
 */
function updateSymlink( $link, $dest, $dryRun ) {
	if ( !file_exists( $dest ) ) {
		fwrite( STDERR, __FUNCTION__ . ": link target $dest does not exist.\n" );
		exit( 1 );
	}

	if ( file_exists( $link ) ) {
		if ( realpath( $link ) === $dest ) {
			echo "$link is already up-to-date.\n";
			return;
		}

		if ( !is_link( $link ) ) {
			fwrite( STDERR, __FUNCTION__ . ": $link exists and is not a symbolic link.\n" );
			exit( 1 );
		}

		if ( !$dryRun && !unlink( $link ) ) {
			fwrite( STDERR, __FUNCTION__ . ": failed to unlink $link\n" );
			exit( 1 );
		}
	}

	if ( !$dryRun && !symlink( $dest, $link ) ) {
		fwrite( STDERR, __FUNCTION__ . ": failed to create $link\n" );
		exit( 1 );
	}
	echo "$link => $dest\n";
}

if ( isMain() ) {
	$dryRun = in_array( '--dry-run', $argv, true );
	updateBranchPointers( $dryRun );
}
