#!/bin/sh
# This script belongs in /home/wikipedia/bin/.
PATH=/bin:/usr/bin:/sbin:/usr/sbin:

umask 0002

echo "Starting l10nupdate at `date`."
if svn up --ignore-externals /home/wikipedia/l10n/trunk/phase3 &&
	svn up --ignore-externals /home/wikipedia/l10n/trunk/extensions
then
	echo "SVN update completed."
else
	/home/wikipedia/bin/dologmsg "!log LocalisationUpdate failed"
	echo "FAILED"
	exit 1
fi

mwVerDbSets=(`mwversionsinuse --extended --withdb`)
if [ -z "$mwVerDbSets" ]; then
	/home/wikipedia/bin/dologmsg "!log LocalisationUpdate failed"
	echo "FAILED"
	exit 1
fi

for i in "${mwVerDbSets[@]}"
do
	mwVerNum=${i%=*}
	mwDbName=${i#*=}
	if mwscript extensions/LocalisationUpdate/update.php \
		  --wiki="$mwDbName" \
		  --outdir=/home/wikipedia/common/php-"$mwVerNum"/cache/l10n \
		  --all \
		  --quiet
	then
		echo "Completed. Syncing to Apaches"
		/home/wikipedia/bin/sync-l10nupdate "$mwVerNum"
		echo "Clearing message blobs"
		mwscript maintenance/wmf/clearMessageBlobs.php --wiki="$mwDbName"
		echo "All done"
	else
		/home/wikipedia/bin/dologmsg "!log LocalisationUpdate failed"
		echo "FAILED"
	fi
done
## Apache clients should sync updates locally every X hours or at scap time
# Not needed anymore as of 3/20/2011 --Roan
