#!/bin/bash

BINDIR=/home/wikipedia/bin
SOURCE=/home/wikipedia/common

# Perform syntax check

if [ ! -S "$SSH_AUTH_SOCK" ]; then
	echo >&2 "SSH_AUTH_SOCK not set or not pointing to a socket."
	echo >&2 "Did you start your ssh-agent?"
	exit 1
fi

mwVerDbSets=(`mwversionsinuse --withdb`)
if [ -z "$mwVerDbSets" ]; then
	echo "Unable to read wikiversions.dat or it is empty"
	exit 1
fi

echo Checking syntax...
for i in "${mwVerDbSets[@]}"
do
	mwVerNum=${i%=*}
	if ! $BINDIR/lint "$SOURCE"/php-"$mwVerNum"; then
		echo Found syntax errors, cannot sync
		exit
	fi
done

# Update the current machine so that serialization works
$BINDIR/sync-common


for i in "${mwVerDbSets[@]}"
do
	mwVerNum=${i%=*}
	mwDbName=${i#*=}
	# Regenerate the extension message file list
	echo Updating ExtensionMessages.php...
	mwscript mergeMessageFileList.php --wiki="$mwDbName" \
		--list-file=$SOURCE/wmf-config/extension-list \
		--output=$SOURCE/wmf-config/ExtensionMessages-"$mwVerNum".php
done

# Notify
$BINDIR/dologmsg "!log $USER synchronizing Wikimedia installation... $(cd /home/wikipedia/common/php-1.17; svn info|grep ^Revision): $*"


# Copy
$BINDIR/set-group-write

echo Copying style sheets to apaches...
ddsh -F30 -cM -g mediawiki-installation 'if [ -x /home/wikipedia/bin/scap-1skins ]; then echo "/home-mounted apache $(hostname)"; /home/wikipedia/bin/scap-1skins; else /usr/bin/scap-1skins; fi'

echo Copying code to apaches...
ddsh -F30 -cM -g mediawiki-installation 'if [ -x /home/wikipedia/bin/scap-1 ]; then echo "/home-mounted apache $(hostname)"; /home/wikipedia/bin/scap-1; else /usr/bin/scap-1; fi'
echo Finished

$BINDIR/dologmsg "sync done."
