#!/bin/bash

mwVersionNums=(`mwversionsinuse`)
for mwVerNum in "${mwVersionNums[@]}"
do
	sudo -u mwdeploy sh -c "
	rsync -a --no-perms 10.0.5.8::common/php-$mwVerNum/skins/ \
	/usr/local/apache/common-local/php-$mwVerNum/skins && \
	echo ok || \
	echo failed
	"
done
