#!/bin/bash
if [ $HOSTNAME == fenari ]; then
    targetbase=/home/wikipedia/common
else
    targetbase=/apache/common
fi

mwVersionNums=`mwversionsinuse --home`
for mwVerNum in "${mwVersionNums[@]}"
do
	find "$targetbase"/php-"$mwVerNum" -group wikidev -not -perm -020 -exec chmod g+w '{}' ';'
done

find "$targetbase"/wmf-config -group wikidev -not -perm -020 -exec chmod g+w '{}' ';'
