#!/bin/bash
if [ $HOSTNAME == fenari ]; then
    target2=/home/wikipedia/common/php-1.17
	target3=/home/wikipedia/common/wmf-config
else
    target2=/apache/common/php-1.17
	target3=/apache/common/wmf-config
fi

#find $target1 -group wikidev -not -perm -020 -exec chmod g+w '{}' ';'
find $target2 -group wikidev -not -perm -020 -exec chmod g+w '{}' ';'
find $target3 -group wikidev -not -perm -020 -exec chmod g+w '{}' ';'
