<?php

/**
 * Autogenerated by WikimediaMaintenance/dumpCirrusInterwikiSources.php
 * Do not modify by hand.
 */
return array (
  'default' => array(),
  'afwiki' => 
  array (
    'afwikibooks' => 'b',
    'afwikiquote' => 'q',
    'afwiktionary' => 'wikt',
  ),
  'amwiki' => 
  array (
    'amwiktionary' => 'wikt',
  ),
  'angwiki' => 
  array (
    'angwiktionary' => 'wikt',
  ),
  'anwiki' => 
  array (
    'anwiktionary' => 'wikt',
  ),
  'arwiki' => 
  array (
    'arwikibooks' => 'b',
    'arwikinews' => 'n',
    'arwikiquote' => 'q',
    'arwikisource' => 's',
    'arwikiversity' => 'v',
    'arwiktionary' => 'wikt',
  ),
  'astwiki' => 
  array (
    'astwiktionary' => 'wikt',
  ),
  'aswiki' => 
  array (
    'aswikisource' => 's',
  ),
  'aywiki' => 
  array (
    'aywiktionary' => 'wikt',
  ),
  'azwiki' => 
  array (
    'azwikibooks' => 'b',
    'azwikiquote' => 'q',
    'azwikisource' => 's',
    'azwiktionary' => 'wikt',
  ),
  'bewiki' => 
  array (
    'bewikibooks' => 'b',
    'bewikiquote' => 'q',
    'bewikisource' => 's',
    'bewiktionary' => 'wikt',
  ),
  'bgwiki' => 
  array (
    'bgwikibooks' => 'b',
    'bgwikinews' => 'n',
    'bgwikiquote' => 'q',
    'bgwikisource' => 's',
    'bgwiktionary' => 'wikt',
  ),
  'bnwiki' => 
  array (
    'bnwikibooks' => 'b',
    'bnwikisource' => 's',
    'bnwiktionary' => 'wikt',
  ),
  'brwiki' => 
  array (
    'brwikiquote' => 'q',
    'brwikisource' => 's',
    'brwiktionary' => 'wikt',
  ),
  'bswiki' => 
  array (
    'bswikibooks' => 'b',
    'bswikinews' => 'n',
    'bswikiquote' => 'q',
    'bswikisource' => 's',
    'bswiktionary' => 'wikt',
  ),
  'cawiki' => 
  array (
    'cawikibooks' => 'b',
    'cawikinews' => 'n',
    'cawikiquote' => 'q',
    'cawikisource' => 's',
    'cawiktionary' => 'wikt',
  ),
  'chrwiki' => 
  array (
    'chrwiktionary' => 'wikt',
  ),
  'cowiki' => 
  array (
    'cowiktionary' => 'wikt',
  ),
  'csbwiki' => 
  array (
    'csbwiktionary' => 'wikt',
  ),
  'cswiki' => 
  array (
    'cswikibooks' => 'b',
    'cswikinews' => 'n',
    'cswikiquote' => 'q',
    'cswikisource' => 's',
    'cswikiversity' => 'v',
    'cswiktionary' => 'wikt',
  ),
  'cvwiki' => 
  array (
    'cvwikibooks' => 'b',
  ),
  'cywiki' => 
  array (
    'cywikibooks' => 'b',
    'cywikiquote' => 'q',
    'cywikisource' => 's',
    'cywiktionary' => 'wikt',
  ),
  'dawiki' => 
  array (
    'dawikibooks' => 'b',
    'dawikiquote' => 'q',
    'dawikisource' => 's',
    'dawiktionary' => 'wikt',
  ),
  'dewiki' => 
  array (
    'dewikibooks' => 'b',
    'dewikinews' => 'n',
    'dewikiquote' => 'q',
    'dewikisource' => 's',
    'dewikiversity' => 'v',
    'dewikivoyage' => 'voy',
    'dewiktionary' => 'wikt',
  ),
  'dvwiki' => 
  array (
    'dvwiktionary' => 'wikt',
  ),
  'elwiki' => 
  array (
    'elwikibooks' => 'b',
    'elwikinews' => 'n',
    'elwikiquote' => 'q',
    'elwikisource' => 's',
    'elwikiversity' => 'v',
    'elwikivoyage' => 'voy',
    'elwiktionary' => 'wikt',
  ),
  'enwiki' => 
  array (
    'enwikibooks' => 'b',
    'enwikinews' => 'n',
    'enwikiquote' => 'q',
    'enwikisource' => 's',
    'enwikiversity' => 'v',
    'enwikivoyage' => 'voy',
    'enwiktionary' => 'wikt',
  ),
  'eowiki' => 
  array (
    'eowikibooks' => 'b',
    'eowikinews' => 'n',
    'eowikiquote' => 'q',
    'eowikisource' => 's',
    'eowiktionary' => 'wikt',
  ),
  'eswiki' => 
  array (
    'eswikibooks' => 'b',
    'eswikinews' => 'n',
    'eswikiquote' => 'q',
    'eswikisource' => 's',
    'eswikiversity' => 'v',
    'eswikivoyage' => 'voy',
    'eswiktionary' => 'wikt',
  ),
  'etwiki' => 
  array (
    'etwikibooks' => 'b',
    'etwikiquote' => 'q',
    'etwikisource' => 's',
    'etwiktionary' => 'wikt',
  ),
  'euwiki' => 
  array (
    'euwikibooks' => 'b',
    'euwikiquote' => 'q',
    'euwiktionary' => 'wikt',
  ),
  'fawiki' => 
  array (
    'fawikibooks' => 'b',
    'fawikinews' => 'n',
    'fawikiquote' => 'q',
    'fawikisource' => 's',
    'fawikivoyage' => 'voy',
    'fawiktionary' => 'wikt',
  ),
  'fiwiki' => 
  array (
    'fiwikibooks' => 'b',
    'fiwikinews' => 'n',
    'fiwikiquote' => 'q',
    'fiwikisource' => 's',
    'fiwikiversity' => 'v',
    'fiwiktionary' => 'wikt',
  ),
  'fjwiki' => 
  array (
    'fjwiktionary' => 'wikt',
  ),
  'fowiki' => 
  array (
    'fowikisource' => 's',
    'fowiktionary' => 'wikt',
  ),
  'frwiki' => 
  array (
    'frwikibooks' => 'b',
    'frwikinews' => 'n',
    'frwikiquote' => 'q',
    'frwikisource' => 's',
    'frwikiversity' => 'v',
    'frwikivoyage' => 'voy',
    'frwiktionary' => 'wikt',
  ),
  'fywiki' => 
  array (
    'fywikibooks' => 'b',
    'fywiktionary' => 'wikt',
  ),
  'gawiki' => 
  array (
    'gawiktionary' => 'wikt',
  ),
  'gdwiki' => 
  array (
    'gdwiktionary' => 'wikt',
  ),
  'glwiki' => 
  array (
    'glwikibooks' => 'b',
    'glwikiquote' => 'q',
    'glwikisource' => 's',
    'glwiktionary' => 'wikt',
  ),
  'gnwiki' => 
  array (
    'gnwiktionary' => 'wikt',
  ),
  'guwiki' => 
  array (
    'guwikiquote' => 'q',
    'guwikisource' => 's',
    'guwiktionary' => 'wikt',
  ),
  'gvwiki' => 
  array (
    'gvwiktionary' => 'wikt',
  ),
  'hawiki' => 
  array (
    'hawiktionary' => 'wikt',
  ),
  'hewiki' => 
  array (
    'hewikibooks' => 'b',
    'hewikinews' => 'n',
    'hewikiquote' => 'q',
    'hewikisource' => 's',
    'hewikivoyage' => 'voy',
    'hewiktionary' => 'wikt',
  ),
  'hiwiki' => 
  array (
    'hiwikibooks' => 'b',
    'hiwikiquote' => 'q',
    'hiwiktionary' => 'wikt',
  ),
  'hrwiki' => 
  array (
    'hrwikibooks' => 'b',
    'hrwikiquote' => 'q',
    'hrwikisource' => 's',
    'hrwiktionary' => 'wikt',
  ),
  'hsbwiki' => 
  array (
    'hsbwiktionary' => 'wikt',
  ),
  'huwiki' => 
  array (
    'huwikibooks' => 'b',
    'huwikiquote' => 'q',
    'huwikisource' => 's',
    'huwiktionary' => 'wikt',
  ),
  'hywiki' => 
  array (
    'hywikibooks' => 'b',
    'hywikiquote' => 'q',
    'hywikisource' => 's',
    'hywiktionary' => 'wikt',
  ),
  'iawiki' => 
  array (
    'iawikibooks' => 'b',
    'iawiktionary' => 'wikt',
  ),
  'idwiki' => 
  array (
    'idwikibooks' => 'b',
    'idwikiquote' => 'q',
    'idwikisource' => 's',
    'idwiktionary' => 'wikt',
  ),
  'iewiki' => 
  array (
    'iewiktionary' => 'wikt',
  ),
  'iowiki' => 
  array (
    'iowiktionary' => 'wikt',
  ),
  'iswiki' => 
  array (
    'iswikibooks' => 'b',
    'iswikiquote' => 'q',
    'iswikisource' => 's',
    'iswiktionary' => 'wikt',
  ),
  'itwiki' => 
  array (
    'itwikibooks' => 'b',
    'itwikinews' => 'n',
    'itwikiquote' => 'q',
    'itwikisource' => 's',
    'itwikiversity' => 'v',
    'itwikivoyage' => 'voy',
    'itwiktionary' => 'wikt',
  ),
  'iuwiki' => 
  array (
    'iuwiktionary' => 'wikt',
  ),
  'jawiki' => 
  array (
    'jawikibooks' => 'b',
    'jawikinews' => 'n',
    'jawikiquote' => 'q',
    'jawikisource' => 's',
    'jawikiversity' => 'v',
    'jawiktionary' => 'wikt',
  ),
  'jbowiki' => 
  array (
    'jbowiktionary' => 'wikt',
  ),
  'jvwiki' => 
  array (
    'jvwiktionary' => 'wikt',
  ),
  'kawiki' => 
  array (
    'kawikibooks' => 'b',
    'kawikiquote' => 'q',
    'kawiktionary' => 'wikt',
  ),
  'kkwiki' => 
  array (
    'kkwikibooks' => 'b',
    'kkwiktionary' => 'wikt',
  ),
  'klwiki' => 
  array (
    'klwiktionary' => 'wikt',
  ),
  'kmwiki' => 
  array (
    'kmwikibooks' => 'b',
    'kmwiktionary' => 'wikt',
  ),
  'knwiki' => 
  array (
    'knwikiquote' => 'q',
    'knwikisource' => 's',
    'knwiktionary' => 'wikt',
  ),
  'kowiki' => 
  array (
    'kowikibooks' => 'b',
    'kowikinews' => 'n',
    'kowikiquote' => 'q',
    'kowikisource' => 's',
    'kowikiversity' => 'v',
    'kowiktionary' => 'wikt',
  ),
  'kswiki' => 
  array (
    'kswiktionary' => 'wikt',
  ),
  'kuwiki' => 
  array (
    'kuwikibooks' => 'b',
    'kuwikiquote' => 'q',
    'kuwiktionary' => 'wikt',
  ),
  'kwwiki' => 
  array (
    'kwwiktionary' => 'wikt',
  ),
  'kywiki' => 
  array (
    'kywikibooks' => 'b',
    'kywikiquote' => 'q',
    'kywiktionary' => 'wikt',
  ),
  'lawiki' => 
  array (
    'lawikibooks' => 'b',
    'lawikiquote' => 'q',
    'lawikisource' => 's',
    'lawiktionary' => 'wikt',
  ),
  'lbwiki' => 
  array (
    'lbwiktionary' => 'wikt',
  ),
  'liwiki' => 
  array (
    'liwikibooks' => 'b',
    'liwikiquote' => 'q',
    'liwikisource' => 's',
    'liwiktionary' => 'wikt',
  ),
  'lnwiki' => 
  array (
    'lnwiktionary' => 'wikt',
  ),
  'lowiki' => 
  array (
    'lowiktionary' => 'wikt',
  ),
  'ltwiki' => 
  array (
    'ltwikibooks' => 'b',
    'ltwikiquote' => 'q',
    'ltwikisource' => 's',
    'ltwiktionary' => 'wikt',
  ),
  'lvwiki' => 
  array (
    'lvwiktionary' => 'wikt',
  ),
  'mgwiki' => 
  array (
    'mgwikibooks' => 'b',
    'mgwiktionary' => 'wikt',
  ),
  'miwiki' => 
  array (
    'miwiktionary' => 'wikt',
  ),
  'mkwiki' => 
  array (
    'mkwikibooks' => 'b',
    'mkwikisource' => 's',
    'mkwiktionary' => 'wikt',
  ),
  'mlwiki' => 
  array (
    'mlwikibooks' => 'b',
    'mlwikiquote' => 'q',
    'mlwikisource' => 's',
    'mlwiktionary' => 'wikt',
  ),
  'mnwiki' => 
  array (
    'mnwiktionary' => 'wikt',
  ),
  'mrwiki' => 
  array (
    'mrwikibooks' => 'b',
    'mrwikiquote' => 'q',
    'mrwikisource' => 's',
    'mrwiktionary' => 'wikt',
  ),
  'mswiki' => 
  array (
    'mswikibooks' => 'b',
    'mswiktionary' => 'wikt',
  ),
  'mtwiki' => 
  array (
    'mtwiktionary' => 'wikt',
  ),
  'mywiki' => 
  array (
    'mywiktionary' => 'wikt',
  ),
  'nahwiki' => 
  array (
    'nahwiktionary' => 'wikt',
  ),
  'nawiki' => 
  array (
    'nawiktionary' => 'wikt',
  ),
  'ndswiki' => 
  array (
    'ndswiktionary' => 'wikt',
  ),
  'newiki' => 
  array (
    'newikibooks' => 'b',
    'newiktionary' => 'wikt',
  ),
  'nlwiki' => 
  array (
    'nlwikibooks' => 'b',
    'nlwikiquote' => 'q',
    'nlwikisource' => 's',
    'nlwikivoyage' => 'voy',
    'nlwiktionary' => 'wikt',
  ),
  'nnwiki' => 
  array (
    'nnwikiquote' => 'q',
    'nnwiktionary' => 'wikt',
  ),
  'nowiki' => 
  array (
    'nowikibooks' => 'b',
    'nowikinews' => 'n',
    'nowikiquote' => 'q',
    'nowikisource' => 's',
    'nowiktionary' => 'wikt',
  ),
  'ocwiki' => 
  array (
    'ocwikibooks' => 'b',
    'ocwiktionary' => 'wikt',
  ),
  'omwiki' => 
  array (
    'omwiktionary' => 'wikt',
  ),
  'orwiki' => 
  array (
    'orwikisource' => 's',
    'orwiktionary' => 'wikt',
  ),
  'pawiki' => 
  array (
    'pawikibooks' => 'b',
    'pawiktionary' => 'wikt',
  ),
  'plwiki' => 
  array (
    'plwikibooks' => 'b',
    'plwikinews' => 'n',
    'plwikiquote' => 'q',
    'plwikisource' => 's',
    'plwikivoyage' => 'voy',
    'plwiktionary' => 'wikt',
  ),
  'pnbwiki' => 
  array (
    'pnbwiktionary' => 'wikt',
  ),
  'pswiki' => 
  array (
    'pswiktionary' => 'wikt',
  ),
  'ptwiki' => 
  array (
    'ptwikibooks' => 'b',
    'ptwikinews' => 'n',
    'ptwikiquote' => 'q',
    'ptwikisource' => 's',
    'ptwikiversity' => 'v',
    'ptwikivoyage' => 'voy',
    'ptwiktionary' => 'wikt',
  ),
  'quwiki' => 
  array (
    'quwiktionary' => 'wikt',
  ),
  'roa_rupwiki' => 
  array (
    'roa_rupwiktionary' => 'wikt',
  ),
  'rowiki' => 
  array (
    'rowikibooks' => 'b',
    'rowikinews' => 'n',
    'rowikiquote' => 'q',
    'rowikisource' => 's',
    'rowikivoyage' => 'voy',
    'rowiktionary' => 'wikt',
  ),
  'ruwiki' => 
  array (
    'ruwikibooks' => 'b',
    'ruwikinews' => 'n',
    'ruwikiquote' => 'q',
    'ruwikisource' => 's',
    'ruwikiversity' => 'v',
    'ruwikivoyage' => 'voy',
    'ruwiktionary' => 'wikt',
  ),
  'rwwiki' => 
  array (
    'rwwiktionary' => 'wikt',
  ),
  'sahwiki' => 
  array (
    'sahwikisource' => 's',
  ),
  'sawiki' => 
  array (
    'sawikibooks' => 'b',
    'sawikiquote' => 'q',
    'sawikisource' => 's',
    'sawiktionary' => 'wikt',
  ),
  'scnwiki' => 
  array (
    'scnwiktionary' => 'wikt',
  ),
  'sdwiki' => 
  array (
    'sdwiktionary' => 'wikt',
  ),
  'sgwiki' => 
  array (
    'sgwiktionary' => 'wikt',
  ),
  'shwiki' => 
  array (
    'shwiktionary' => 'wikt',
  ),
  'simplewiki' => 
  array (
    'simplewiktionary' => 'wikt',
  ),
  'siwiki' => 
  array (
    'siwikibooks' => 'b',
    'siwiktionary' => 'wikt',
  ),
  'skwiki' => 
  array (
    'skwikibooks' => 'b',
    'skwikiquote' => 'q',
    'skwikisource' => 's',
    'skwiktionary' => 'wikt',
  ),
  'slwiki' => 
  array (
    'slwikibooks' => 'b',
    'slwikiquote' => 'q',
    'slwikisource' => 's',
    'slwikiversity' => 'v',
    'slwiktionary' => 'wikt',
  ),
  'smwiki' => 
  array (
    'smwiktionary' => 'wikt',
  ),
  'sowiki' => 
  array (
    'sowiktionary' => 'wikt',
  ),
  'sqwiki' => 
  array (
    'sqwikibooks' => 'b',
    'sqwikinews' => 'n',
    'sqwikiquote' => 'q',
    'sqwiktionary' => 'wikt',
  ),
  'srwiki' => 
  array (
    'srwikibooks' => 'b',
    'srwikinews' => 'n',
    'srwikiquote' => 'q',
    'srwikisource' => 's',
    'srwiktionary' => 'wikt',
  ),
  'sswiki' => 
  array (
    'sswiktionary' => 'wikt',
  ),
  'stwiki' => 
  array (
    'stwiktionary' => 'wikt',
  ),
  'suwiki' => 
  array (
    'suwikiquote' => 'q',
    'suwiktionary' => 'wikt',
  ),
  'svwiki' => 
  array (
    'svwikibooks' => 'b',
    'svwikinews' => 'n',
    'svwikiquote' => 'q',
    'svwikisource' => 's',
    'svwikiversity' => 'v',
    'svwikivoyage' => 'voy',
    'svwiktionary' => 'wikt',
  ),
  'swwiki' => 
  array (
    'swwiktionary' => 'wikt',
  ),
  'tawiki' => 
  array (
    'tawikibooks' => 'b',
    'tawikinews' => 'n',
    'tawikiquote' => 'q',
    'tawikisource' => 's',
    'tawiktionary' => 'wikt',
  ),
  'tewiki' => 
  array (
    'tewikibooks' => 'b',
    'tewikiquote' => 'q',
    'tewikisource' => 's',
    'tewiktionary' => 'wikt',
  ),
  'tgwiki' => 
  array (
    'tgwikibooks' => 'b',
    'tgwiktionary' => 'wikt',
  ),
  'thwiki' => 
  array (
    'thwikibooks' => 'b',
    'thwikiquote' => 'q',
    'thwikisource' => 's',
    'thwiktionary' => 'wikt',
  ),
  'tiwiki' => 
  array (
    'tiwiktionary' => 'wikt',
  ),
  'tkwiki' => 
  array (
    'tkwiktionary' => 'wikt',
  ),
  'tlwiki' => 
  array (
    'tlwikibooks' => 'b',
    'tlwiktionary' => 'wikt',
  ),
  'tnwiki' => 
  array (
    'tnwiktionary' => 'wikt',
  ),
  'tpiwiki' => 
  array (
    'tpiwiktionary' => 'wikt',
  ),
  'trwiki' => 
  array (
    'trwikibooks' => 'b',
    'trwikinews' => 'n',
    'trwikiquote' => 'q',
    'trwikisource' => 's',
    'trwiktionary' => 'wikt',
  ),
  'tswiki' => 
  array (
    'tswiktionary' => 'wikt',
  ),
  'ttwiki' => 
  array (
    'ttwikibooks' => 'b',
    'ttwiktionary' => 'wikt',
  ),
  'ugwiki' => 
  array (
    'ugwiktionary' => 'wikt',
  ),
  'ukwiki' => 
  array (
    'ukwikibooks' => 'b',
    'ukwikinews' => 'n',
    'ukwikiquote' => 'q',
    'ukwikisource' => 's',
    'ukwikivoyage' => 'voy',
    'ukwiktionary' => 'wikt',
  ),
  'urwiki' => 
  array (
    'urwikibooks' => 'b',
    'urwikiquote' => 'q',
    'urwiktionary' => 'wikt',
  ),
  'uzwiki' => 
  array (
    'uzwikiquote' => 'q',
    'uzwiktionary' => 'wikt',
  ),
  'vecwiki' => 
  array (
    'vecwikisource' => 's',
    'vecwiktionary' => 'wikt',
  ),
  'viwiki' => 
  array (
    'viwikibooks' => 'b',
    'viwikiquote' => 'q',
    'viwikisource' => 's',
    'viwikivoyage' => 'voy',
    'viwiktionary' => 'wikt',
  ),
  'vowiki' => 
  array (
    'vowiktionary' => 'wikt',
  ),
  'wawiki' => 
  array (
    'wawiktionary' => 'wikt',
  ),
  'wowiki' => 
  array (
    'wowikiquote' => 'q',
    'wowiktionary' => 'wikt',
  ),
  'yiwiki' => 
  array (
    'yiwikisource' => 's',
    'yiwiktionary' => 'wikt',
  ),
  'zh_min_nanwiki' => 
  array (
    'zh_min_nanwikisource' => 's',
    'zh_min_nanwiktionary' => 'wikt',
  ),
  'zhwiki' => 
  array (
    'zhwikibooks' => 'b',
    'zhwikinews' => 'n',
    'zhwikiquote' => 'q',
    'zhwikisource' => 's',
    'zhwikivoyage' => 'voy',
    'zhwiktionary' => 'wikt',
  ),
  'zuwiki' => 
  array (
    'zuwiktionary' => 'wikt',
  ),
);
