<?php

/**
 * Autogenerated by WikimediaMaintenance/dumpCirrusInterwikiSources.php
 * Do not modify by hand.
 */
return array (
  'default' => 
  array (
  ),
  'afwiki' => 
  array (
    'b' => 'afwikibooks',
    'q' => 'afwikiquote',
    'wikt' => 'afwiktionary',
  ),
  'amwiki' => 
  array (
    'wikt' => 'amwiktionary',
  ),
  'angwiki' => 
  array (
    'wikt' => 'angwiktionary',
  ),
  'anwiki' => 
  array (
    'wikt' => 'anwiktionary',
  ),
  'arwiki' => 
  array (
    'b' => 'arwikibooks',
    'n' => 'arwikinews',
    'q' => 'arwikiquote',
    's' => 'arwikisource',
    'v' => 'arwikiversity',
    'wikt' => 'arwiktionary',
  ),
  'astwiki' => 
  array (
    'wikt' => 'astwiktionary',
  ),
  'aswiki' => 
  array (
    's' => 'aswikisource',
  ),
  'aywiki' => 
  array (
    'wikt' => 'aywiktionary',
  ),
  'azwiki' => 
  array (
    'b' => 'azwikibooks',
    'q' => 'azwikiquote',
    's' => 'azwikisource',
    'wikt' => 'azwiktionary',
  ),
  'bewiki' => 
  array (
    'b' => 'bewikibooks',
    'q' => 'bewikiquote',
    's' => 'bewikisource',
    'wikt' => 'bewiktionary',
  ),
  'bgwiki' => 
  array (
    'b' => 'bgwikibooks',
    'n' => 'bgwikinews',
    'q' => 'bgwikiquote',
    's' => 'bgwikisource',
    'wikt' => 'bgwiktionary',
  ),
  'bnwiki' => 
  array (
    'b' => 'bnwikibooks',
    's' => 'bnwikisource',
    'wikt' => 'bnwiktionary',
  ),
  'brwiki' => 
  array (
    'q' => 'brwikiquote',
    's' => 'brwikisource',
    'wikt' => 'brwiktionary',
  ),
  'bswiki' => 
  array (
    'b' => 'bswikibooks',
    'n' => 'bswikinews',
    'q' => 'bswikiquote',
    's' => 'bswikisource',
    'wikt' => 'bswiktionary',
  ),
  'cawiki' => 
  array (
    'b' => 'cawikibooks',
    'n' => 'cawikinews',
    'q' => 'cawikiquote',
    's' => 'cawikisource',
    'wikt' => 'cawiktionary',
  ),
  'chrwiki' => 
  array (
    'wikt' => 'chrwiktionary',
  ),
  'cowiki' => 
  array (
    'wikt' => 'cowiktionary',
  ),
  'csbwiki' => 
  array (
    'wikt' => 'csbwiktionary',
  ),
  'cswiki' => 
  array (
    'b' => 'cswikibooks',
    'n' => 'cswikinews',
    'q' => 'cswikiquote',
    's' => 'cswikisource',
    'v' => 'cswikiversity',
    'wikt' => 'cswiktionary',
  ),
  'cvwiki' => 
  array (
    'b' => 'cvwikibooks',
  ),
  'cywiki' => 
  array (
    'b' => 'cywikibooks',
    'q' => 'cywikiquote',
    's' => 'cywikisource',
    'wikt' => 'cywiktionary',
  ),
  'dawiki' => 
  array (
    'b' => 'dawikibooks',
    'q' => 'dawikiquote',
    's' => 'dawikisource',
    'wikt' => 'dawiktionary',
  ),
  'dewiki' => 
  array (
    'b' => 'dewikibooks',
    'n' => 'dewikinews',
    'q' => 'dewikiquote',
    's' => 'dewikisource',
    'v' => 'dewikiversity',
    'voy' => 'dewikivoyage',
    'wikt' => 'dewiktionary',
  ),
  'dvwiki' => 
  array (
    'wikt' => 'dvwiktionary',
  ),
  'elwiki' => 
  array (
    'b' => 'elwikibooks',
    'n' => 'elwikinews',
    'q' => 'elwikiquote',
    's' => 'elwikisource',
    'v' => 'elwikiversity',
    'voy' => 'elwikivoyage',
    'wikt' => 'elwiktionary',
  ),
  'enwiki' => 
  array (
    'b' => 'enwikibooks',
    'n' => 'enwikinews',
    'q' => 'enwikiquote',
    's' => 'enwikisource',
    'v' => 'enwikiversity',
    'voy' => 'enwikivoyage',
    'wikt' => 'enwiktionary',
  ),
  'eowiki' => 
  array (
    'b' => 'eowikibooks',
    'n' => 'eowikinews',
    'q' => 'eowikiquote',
    's' => 'eowikisource',
    'wikt' => 'eowiktionary',
  ),
  'eswiki' => 
  array (
    'b' => 'eswikibooks',
    'n' => 'eswikinews',
    'q' => 'eswikiquote',
    's' => 'eswikisource',
    'v' => 'eswikiversity',
    'voy' => 'eswikivoyage',
    'wikt' => 'eswiktionary',
  ),
  'etwiki' => 
  array (
    'b' => 'etwikibooks',
    'q' => 'etwikiquote',
    's' => 'etwikisource',
    'wikt' => 'etwiktionary',
  ),
  'euwiki' => 
  array (
    'b' => 'euwikibooks',
    'q' => 'euwikiquote',
    'wikt' => 'euwiktionary',
  ),
  'fawiki' => 
  array (
    'b' => 'fawikibooks',
    'n' => 'fawikinews',
    'q' => 'fawikiquote',
    's' => 'fawikisource',
    'voy' => 'fawikivoyage',
    'wikt' => 'fawiktionary',
  ),
  'fiwiki' => 
  array (
    'b' => 'fiwikibooks',
    'n' => 'fiwikinews',
    'q' => 'fiwikiquote',
    's' => 'fiwikisource',
    'v' => 'fiwikiversity',
    'wikt' => 'fiwiktionary',
  ),
  'fjwiki' => 
  array (
    'wikt' => 'fjwiktionary',
  ),
  'fowiki' => 
  array (
    's' => 'fowikisource',
    'wikt' => 'fowiktionary',
  ),
  'frwiki' => 
  array (
    'b' => 'frwikibooks',
    'n' => 'frwikinews',
    'q' => 'frwikiquote',
    's' => 'frwikisource',
    'v' => 'frwikiversity',
    'voy' => 'frwikivoyage',
    'wikt' => 'frwiktionary',
  ),
  'fywiki' => 
  array (
    'b' => 'fywikibooks',
    'wikt' => 'fywiktionary',
  ),
  'gawiki' => 
  array (
    'wikt' => 'gawiktionary',
  ),
  'gdwiki' => 
  array (
    'wikt' => 'gdwiktionary',
  ),
  'glwiki' => 
  array (
    'b' => 'glwikibooks',
    'q' => 'glwikiquote',
    's' => 'glwikisource',
    'wikt' => 'glwiktionary',
  ),
  'gnwiki' => 
  array (
    'wikt' => 'gnwiktionary',
  ),
  'guwiki' => 
  array (
    'q' => 'guwikiquote',
    's' => 'guwikisource',
    'wikt' => 'guwiktionary',
  ),
  'gvwiki' => 
  array (
    'wikt' => 'gvwiktionary',
  ),
  'hawiki' => 
  array (
    'wikt' => 'hawiktionary',
  ),
  'hewiki' => 
  array (
    'b' => 'hewikibooks',
    'n' => 'hewikinews',
    'q' => 'hewikiquote',
    's' => 'hewikisource',
    'voy' => 'hewikivoyage',
    'wikt' => 'hewiktionary',
  ),
  'hiwiki' => 
  array (
    'b' => 'hiwikibooks',
    'q' => 'hiwikiquote',
    'wikt' => 'hiwiktionary',
  ),
  'hrwiki' => 
  array (
    'b' => 'hrwikibooks',
    'q' => 'hrwikiquote',
    's' => 'hrwikisource',
    'wikt' => 'hrwiktionary',
  ),
  'hsbwiki' => 
  array (
    'wikt' => 'hsbwiktionary',
  ),
  'huwiki' => 
  array (
    'b' => 'huwikibooks',
    'q' => 'huwikiquote',
    's' => 'huwikisource',
    'wikt' => 'huwiktionary',
  ),
  'hywiki' => 
  array (
    'b' => 'hywikibooks',
    'q' => 'hywikiquote',
    's' => 'hywikisource',
    'wikt' => 'hywiktionary',
  ),
  'iawiki' => 
  array (
    'b' => 'iawikibooks',
    'wikt' => 'iawiktionary',
  ),
  'idwiki' => 
  array (
    'b' => 'idwikibooks',
    'q' => 'idwikiquote',
    's' => 'idwikisource',
    'wikt' => 'idwiktionary',
  ),
  'iewiki' => 
  array (
    'wikt' => 'iewiktionary',
  ),
  'iowiki' => 
  array (
    'wikt' => 'iowiktionary',
  ),
  'iswiki' => 
  array (
    'b' => 'iswikibooks',
    'q' => 'iswikiquote',
    's' => 'iswikisource',
    'wikt' => 'iswiktionary',
  ),
  'itwiki' => 
  array (
    'b' => 'itwikibooks',
    'n' => 'itwikinews',
    'q' => 'itwikiquote',
    's' => 'itwikisource',
    'v' => 'itwikiversity',
    'voy' => 'itwikivoyage',
    'wikt' => 'itwiktionary',
  ),
  'iuwiki' => 
  array (
    'wikt' => 'iuwiktionary',
  ),
  'jawiki' => 
  array (
    'b' => 'jawikibooks',
    'n' => 'jawikinews',
    'q' => 'jawikiquote',
    's' => 'jawikisource',
    'v' => 'jawikiversity',
    'wikt' => 'jawiktionary',
  ),
  'jbowiki' => 
  array (
    'wikt' => 'jbowiktionary',
  ),
  'jvwiki' => 
  array (
    'wikt' => 'jvwiktionary',
  ),
  'kawiki' => 
  array (
    'b' => 'kawikibooks',
    'q' => 'kawikiquote',
    'wikt' => 'kawiktionary',
  ),
  'kkwiki' => 
  array (
    'b' => 'kkwikibooks',
    'wikt' => 'kkwiktionary',
  ),
  'klwiki' => 
  array (
    'wikt' => 'klwiktionary',
  ),
  'kmwiki' => 
  array (
    'b' => 'kmwikibooks',
    'wikt' => 'kmwiktionary',
  ),
  'knwiki' => 
  array (
    'q' => 'knwikiquote',
    's' => 'knwikisource',
    'wikt' => 'knwiktionary',
  ),
  'kowiki' => 
  array (
    'b' => 'kowikibooks',
    'n' => 'kowikinews',
    'q' => 'kowikiquote',
    's' => 'kowikisource',
    'v' => 'kowikiversity',
    'wikt' => 'kowiktionary',
  ),
  'kswiki' => 
  array (
    'wikt' => 'kswiktionary',
  ),
  'kuwiki' => 
  array (
    'b' => 'kuwikibooks',
    'q' => 'kuwikiquote',
    'wikt' => 'kuwiktionary',
  ),
  'kwwiki' => 
  array (
    'wikt' => 'kwwiktionary',
  ),
  'kywiki' => 
  array (
    'b' => 'kywikibooks',
    'q' => 'kywikiquote',
    'wikt' => 'kywiktionary',
  ),
  'lawiki' => 
  array (
    'b' => 'lawikibooks',
    'q' => 'lawikiquote',
    's' => 'lawikisource',
    'wikt' => 'lawiktionary',
  ),
  'lbwiki' => 
  array (
    'wikt' => 'lbwiktionary',
  ),
  'liwiki' => 
  array (
    'b' => 'liwikibooks',
    'q' => 'liwikiquote',
    's' => 'liwikisource',
    'wikt' => 'liwiktionary',
  ),
  'lnwiki' => 
  array (
    'wikt' => 'lnwiktionary',
  ),
  'lowiki' => 
  array (
    'wikt' => 'lowiktionary',
  ),
  'ltwiki' => 
  array (
    'b' => 'ltwikibooks',
    'q' => 'ltwikiquote',
    's' => 'ltwikisource',
    'wikt' => 'ltwiktionary',
  ),
  'lvwiki' => 
  array (
    'wikt' => 'lvwiktionary',
  ),
  'mgwiki' => 
  array (
    'b' => 'mgwikibooks',
    'wikt' => 'mgwiktionary',
  ),
  'miwiki' => 
  array (
    'wikt' => 'miwiktionary',
  ),
  'mkwiki' => 
  array (
    'b' => 'mkwikibooks',
    's' => 'mkwikisource',
    'wikt' => 'mkwiktionary',
  ),
  'mlwiki' => 
  array (
    'b' => 'mlwikibooks',
    'q' => 'mlwikiquote',
    's' => 'mlwikisource',
    'wikt' => 'mlwiktionary',
  ),
  'mnwiki' => 
  array (
    'wikt' => 'mnwiktionary',
  ),
  'mrwiki' => 
  array (
    'b' => 'mrwikibooks',
    'q' => 'mrwikiquote',
    's' => 'mrwikisource',
    'wikt' => 'mrwiktionary',
  ),
  'mswiki' => 
  array (
    'b' => 'mswikibooks',
    'wikt' => 'mswiktionary',
  ),
  'mtwiki' => 
  array (
    'wikt' => 'mtwiktionary',
  ),
  'mywiki' => 
  array (
    'wikt' => 'mywiktionary',
  ),
  'nahwiki' => 
  array (
    'wikt' => 'nahwiktionary',
  ),
  'nawiki' => 
  array (
    'wikt' => 'nawiktionary',
  ),
  'ndswiki' => 
  array (
    'wikt' => 'ndswiktionary',
  ),
  'newiki' => 
  array (
    'b' => 'newikibooks',
    'wikt' => 'newiktionary',
  ),
  'nlwiki' => 
  array (
    'b' => 'nlwikibooks',
    'q' => 'nlwikiquote',
    's' => 'nlwikisource',
    'voy' => 'nlwikivoyage',
    'wikt' => 'nlwiktionary',
  ),
  'nnwiki' => 
  array (
    'q' => 'nnwikiquote',
    'wikt' => 'nnwiktionary',
  ),
  'nowiki' => 
  array (
    'b' => 'nowikibooks',
    'n' => 'nowikinews',
    'q' => 'nowikiquote',
    's' => 'nowikisource',
    'wikt' => 'nowiktionary',
  ),
  'ocwiki' => 
  array (
    'b' => 'ocwikibooks',
    'wikt' => 'ocwiktionary',
  ),
  'omwiki' => 
  array (
    'wikt' => 'omwiktionary',
  ),
  'orwiki' => 
  array (
    's' => 'orwikisource',
    'wikt' => 'orwiktionary',
  ),
  'pawiki' => 
  array (
    'b' => 'pawikibooks',
    'wikt' => 'pawiktionary',
  ),
  'plwiki' => 
  array (
    'b' => 'plwikibooks',
    'n' => 'plwikinews',
    'q' => 'plwikiquote',
    's' => 'plwikisource',
    'voy' => 'plwikivoyage',
    'wikt' => 'plwiktionary',
  ),
  'pnbwiki' => 
  array (
    'wikt' => 'pnbwiktionary',
  ),
  'pswiki' => 
  array (
    'wikt' => 'pswiktionary',
  ),
  'ptwiki' => 
  array (
    'b' => 'ptwikibooks',
    'n' => 'ptwikinews',
    'q' => 'ptwikiquote',
    's' => 'ptwikisource',
    'v' => 'ptwikiversity',
    'voy' => 'ptwikivoyage',
    'wikt' => 'ptwiktionary',
  ),
  'quwiki' => 
  array (
    'wikt' => 'quwiktionary',
  ),
  'roa_rupwiki' => 
  array (
    'wikt' => 'roa_rupwiktionary',
  ),
  'rowiki' => 
  array (
    'b' => 'rowikibooks',
    'n' => 'rowikinews',
    'q' => 'rowikiquote',
    's' => 'rowikisource',
    'voy' => 'rowikivoyage',
    'wikt' => 'rowiktionary',
  ),
  'ruwiki' => 
  array (
    'b' => 'ruwikibooks',
    'n' => 'ruwikinews',
    'q' => 'ruwikiquote',
    's' => 'ruwikisource',
    'v' => 'ruwikiversity',
    'voy' => 'ruwikivoyage',
    'wikt' => 'ruwiktionary',
  ),
  'rwwiki' => 
  array (
    'wikt' => 'rwwiktionary',
  ),
  'sahwiki' => 
  array (
    's' => 'sahwikisource',
  ),
  'sawiki' => 
  array (
    'b' => 'sawikibooks',
    'q' => 'sawikiquote',
    's' => 'sawikisource',
    'wikt' => 'sawiktionary',
  ),
  'scnwiki' => 
  array (
    'wikt' => 'scnwiktionary',
  ),
  'sdwiki' => 
  array (
    'wikt' => 'sdwiktionary',
  ),
  'sgwiki' => 
  array (
    'wikt' => 'sgwiktionary',
  ),
  'shwiki' => 
  array (
    'wikt' => 'shwiktionary',
  ),
  'simplewiki' => 
  array (
    'wikt' => 'simplewiktionary',
  ),
  'siwiki' => 
  array (
    'b' => 'siwikibooks',
    'wikt' => 'siwiktionary',
  ),
  'skwiki' => 
  array (
    'b' => 'skwikibooks',
    'q' => 'skwikiquote',
    's' => 'skwikisource',
    'wikt' => 'skwiktionary',
  ),
  'slwiki' => 
  array (
    'b' => 'slwikibooks',
    'q' => 'slwikiquote',
    's' => 'slwikisource',
    'v' => 'slwikiversity',
    'wikt' => 'slwiktionary',
  ),
  'smwiki' => 
  array (
    'wikt' => 'smwiktionary',
  ),
  'sowiki' => 
  array (
    'wikt' => 'sowiktionary',
  ),
  'sqwiki' => 
  array (
    'b' => 'sqwikibooks',
    'n' => 'sqwikinews',
    'q' => 'sqwikiquote',
    'wikt' => 'sqwiktionary',
  ),
  'srwiki' => 
  array (
    'b' => 'srwikibooks',
    'n' => 'srwikinews',
    'q' => 'srwikiquote',
    's' => 'srwikisource',
    'wikt' => 'srwiktionary',
  ),
  'sswiki' => 
  array (
    'wikt' => 'sswiktionary',
  ),
  'stwiki' => 
  array (
    'wikt' => 'stwiktionary',
  ),
  'suwiki' => 
  array (
    'q' => 'suwikiquote',
    'wikt' => 'suwiktionary',
  ),
  'svwiki' => 
  array (
    'b' => 'svwikibooks',
    'n' => 'svwikinews',
    'q' => 'svwikiquote',
    's' => 'svwikisource',
    'v' => 'svwikiversity',
    'voy' => 'svwikivoyage',
    'wikt' => 'svwiktionary',
  ),
  'swwiki' => 
  array (
    'wikt' => 'swwiktionary',
  ),
  'tawiki' => 
  array (
    'b' => 'tawikibooks',
    'n' => 'tawikinews',
    'q' => 'tawikiquote',
    's' => 'tawikisource',
    'wikt' => 'tawiktionary',
  ),
  'tewiki' => 
  array (
    'b' => 'tewikibooks',
    'q' => 'tewikiquote',
    's' => 'tewikisource',
    'wikt' => 'tewiktionary',
  ),
  'tgwiki' => 
  array (
    'b' => 'tgwikibooks',
    'wikt' => 'tgwiktionary',
  ),
  'thwiki' => 
  array (
    'b' => 'thwikibooks',
    'q' => 'thwikiquote',
    's' => 'thwikisource',
    'wikt' => 'thwiktionary',
  ),
  'tiwiki' => 
  array (
    'wikt' => 'tiwiktionary',
  ),
  'tkwiki' => 
  array (
    'wikt' => 'tkwiktionary',
  ),
  'tlwiki' => 
  array (
    'b' => 'tlwikibooks',
    'wikt' => 'tlwiktionary',
  ),
  'tnwiki' => 
  array (
    'wikt' => 'tnwiktionary',
  ),
  'tpiwiki' => 
  array (
    'wikt' => 'tpiwiktionary',
  ),
  'trwiki' => 
  array (
    'b' => 'trwikibooks',
    'n' => 'trwikinews',
    'q' => 'trwikiquote',
    's' => 'trwikisource',
    'wikt' => 'trwiktionary',
  ),
  'tswiki' => 
  array (
    'wikt' => 'tswiktionary',
  ),
  'ttwiki' => 
  array (
    'b' => 'ttwikibooks',
    'wikt' => 'ttwiktionary',
  ),
  'ugwiki' => 
  array (
    'wikt' => 'ugwiktionary',
  ),
  'ukwiki' => 
  array (
    'b' => 'ukwikibooks',
    'n' => 'ukwikinews',
    'q' => 'ukwikiquote',
    's' => 'ukwikisource',
    'voy' => 'ukwikivoyage',
    'wikt' => 'ukwiktionary',
  ),
  'urwiki' => 
  array (
    'b' => 'urwikibooks',
    'q' => 'urwikiquote',
    'wikt' => 'urwiktionary',
  ),
  'uzwiki' => 
  array (
    'q' => 'uzwikiquote',
    'wikt' => 'uzwiktionary',
  ),
  'vecwiki' => 
  array (
    's' => 'vecwikisource',
    'wikt' => 'vecwiktionary',
  ),
  'viwiki' => 
  array (
    'b' => 'viwikibooks',
    'q' => 'viwikiquote',
    's' => 'viwikisource',
    'voy' => 'viwikivoyage',
    'wikt' => 'viwiktionary',
  ),
  'vowiki' => 
  array (
    'wikt' => 'vowiktionary',
  ),
  'wawiki' => 
  array (
    'wikt' => 'wawiktionary',
  ),
  'wowiki' => 
  array (
    'q' => 'wowikiquote',
    'wikt' => 'wowiktionary',
  ),
  'yiwiki' => 
  array (
    's' => 'yiwikisource',
    'wikt' => 'yiwiktionary',
  ),
  'zh_min_nanwiki' => 
  array (
    's' => 'zh_min_nanwikisource',
    'wikt' => 'zh_min_nanwiktionary',
  ),
  'zhwiki' => 
  array (
    'b' => 'zhwikibooks',
    'n' => 'zhwikinews',
    'q' => 'zhwikiquote',
    's' => 'zhwikisource',
    'voy' => 'zhwikivoyage',
    'wikt' => 'zhwiktionary',
  ),
  'zuwiki' => 
  array (
    'wikt' => 'zuwiktionary',
  ),
);