<?php

/**
 * Autogenerated by WikimediaMaintenance/dumpCirrusInterwikiSources.php
 * Do not modify by hand.
 */
return array (
  'default' => array(),
  'abwiki' =>
  array (
    'abwiki' => 'w',
  ),
  'acewiki' =>
  array (
    'acewiki' => 'w',
  ),
  'adywiki' =>
  array (
    'adywiki' => 'w',
  ),
  'afwiki' =>
  array (
    'afwiki' => 'w',
    'afwikibooks' => 'b',
    'afwikiquote' => 'q',
    'afwiktionary' => 'wikt',
  ),
  'akwiki' =>
  array (
    'akwiki' => 'w',
  ),
  'alswiki' =>
  array (
    'alswiki' => 'w',
  ),
  'amwiki' =>
  array (
    'amwiki' => 'w',
    'amwiktionary' => 'wikt',
  ),
  'angwiki' =>
  array (
    'angwiki' => 'w',
    'angwiktionary' => 'wikt',
  ),
  'anwiki' =>
  array (
    'anwiki' => 'w',
    'anwiktionary' => 'wikt',
  ),
  'arcwiki' =>
  array (
    'arcwiki' => 'w',
  ),
  'arwiki' =>
  array (
    'arwiki' => 'w',
    'arwikibooks' => 'b',
    'arwikinews' => 'n',
    'arwikiquote' => 'q',
    'arwikisource' => 's',
    'arwikiversity' => 'v',
    'arwiktionary' => 'wikt',
  ),
  'arzwiki' =>
  array (
    'arzwiki' => 'w',
  ),
  'astwiki' =>
  array (
    'astwiki' => 'w',
    'astwiktionary' => 'wikt',
  ),
  'aswiki' =>
  array (
    'aswiki' => 'w',
    'aswikisource' => 's',
  ),
  'avwiki' =>
  array (
    'avwiki' => 'w',
  ),
  'aywiki' =>
  array (
    'aywiki' => 'w',
    'aywiktionary' => 'wikt',
  ),
  'azbwiki' =>
  array (
    'azbwiki' => 'w',
  ),
  'azwiki' =>
  array (
    'azwiki' => 'w',
    'azwikibooks' => 'b',
    'azwikiquote' => 'q',
    'azwikisource' => 's',
    'azwiktionary' => 'wikt',
  ),
  'barwiki' =>
  array (
    'barwiki' => 'w',
  ),
  'bat_smgwiki' =>
  array (
    'bat_smgwiki' => 'w',
  ),
  'bawiki' =>
  array (
    'bawiki' => 'w',
  ),
  'bclwiki' =>
  array (
    'bclwiki' => 'w',
  ),
  'be_x_oldwiki' =>
  array (
    'be_x_oldwiki' => 'w',
  ),
  'bewiki' =>
  array (
    'bewiki' => 'w',
    'bewikibooks' => 'b',
    'bewikiquote' => 'q',
    'bewikisource' => 's',
    'bewiktionary' => 'wikt',
  ),
  'bgwiki' =>
  array (
    'bgwiki' => 'w',
    'bgwikibooks' => 'b',
    'bgwikinews' => 'n',
    'bgwikiquote' => 'q',
    'bgwikisource' => 's',
    'bgwiktionary' => 'wikt',
  ),
  'bhwiki' =>
  array (
    'bhwiki' => 'w',
  ),
  'biwiki' =>
  array (
    'biwiki' => 'w',
  ),
  'bjnwiki' =>
  array (
    'bjnwiki' => 'w',
  ),
  'bmwiki' =>
  array (
    'bmwiki' => 'w',
  ),
  'bnwiki' =>
  array (
    'bnwiki' => 'w',
    'bnwikibooks' => 'b',
    'bnwikisource' => 's',
    'bnwiktionary' => 'wikt',
  ),
  'bowiki' =>
  array (
    'bowiki' => 'w',
  ),
  'bpywiki' =>
  array (
    'bpywiki' => 'w',
  ),
  'brwiki' =>
  array (
    'brwiki' => 'w',
    'brwikiquote' => 'q',
    'brwikisource' => 's',
    'brwiktionary' => 'wikt',
  ),
  'bswiki' =>
  array (
    'bswiki' => 'w',
    'bswikibooks' => 'b',
    'bswikinews' => 'n',
    'bswikiquote' => 'q',
    'bswikisource' => 's',
    'bswiktionary' => 'wikt',
  ),
  'bugwiki' =>
  array (
    'bugwiki' => 'w',
  ),
  'bxrwiki' =>
  array (
    'bxrwiki' => 'w',
  ),
  'cawiki' =>
  array (
    'cawiki' => 'w',
    'cawikibooks' => 'b',
    'cawikinews' => 'n',
    'cawikiquote' => 'q',
    'cawikisource' => 's',
    'cawiktionary' => 'wikt',
  ),
  'cbk_zamwiki' =>
  array (
    'cbk_zamwiki' => 'w',
  ),
  'cdowiki' =>
  array (
    'cdowiki' => 'w',
  ),
  'cebwiki' =>
  array (
    'cebwiki' => 'w',
  ),
  'cewiki' =>
  array (
    'cewiki' => 'w',
  ),
  'chrwiki' =>
  array (
    'chrwiki' => 'w',
    'chrwiktionary' => 'wikt',
  ),
  'chwiki' =>
  array (
    'chwiki' => 'w',
  ),
  'chywiki' =>
  array (
    'chywiki' => 'w',
  ),
  'ckbwiki' =>
  array (
    'ckbwiki' => 'w',
  ),
  'cowiki' =>
  array (
    'cowiki' => 'w',
    'cowiktionary' => 'wikt',
  ),
  'crhwiki' =>
  array (
    'crhwiki' => 'w',
  ),
  'crwiki' =>
  array (
    'crwiki' => 'w',
  ),
  'csbwiki' =>
  array (
    'csbwiki' => 'w',
    'csbwiktionary' => 'wikt',
  ),
  'cswiki' =>
  array (
    'cswiki' => 'w',
    'cswikibooks' => 'b',
    'cswikinews' => 'n',
    'cswikiquote' => 'q',
    'cswikisource' => 's',
    'cswikiversity' => 'v',
    'cswiktionary' => 'wikt',
  ),
  'cuwiki' =>
  array (
    'cuwiki' => 'w',
  ),
  'cvwiki' =>
  array (
    'cvwiki' => 'w',
    'cvwikibooks' => 'b',
  ),
  'cywiki' =>
  array (
    'cywiki' => 'w',
    'cywikibooks' => 'b',
    'cywikiquote' => 'q',
    'cywikisource' => 's',
    'cywiktionary' => 'wikt',
  ),
  'dawiki' =>
  array (
    'dawiki' => 'w',
    'dawikibooks' => 'b',
    'dawikiquote' => 'q',
    'dawikisource' => 's',
    'dawiktionary' => 'wikt',
  ),
  'dewiki' =>
  array (
    'dewiki' => 'w',
    'dewikibooks' => 'b',
    'dewikinews' => 'n',
    'dewikiquote' => 'q',
    'dewikisource' => 's',
    'dewikiversity' => 'v',
    'dewikivoyage' => 'voy',
    'dewiktionary' => 'wikt',
  ),
  'diqwiki' =>
  array (
    'diqwiki' => 'w',
  ),
  'dsbwiki' =>
  array (
    'dsbwiki' => 'w',
  ),
  'dvwiki' =>
  array (
    'dvwiki' => 'w',
    'dvwiktionary' => 'wikt',
  ),
  'dzwiki' =>
  array (
    'dzwiki' => 'w',
  ),
  'eewiki' =>
  array (
    'eewiki' => 'w',
  ),
  'elwiki' =>
  array (
    'elwiki' => 'w',
    'elwikibooks' => 'b',
    'elwikinews' => 'n',
    'elwikiquote' => 'q',
    'elwikisource' => 's',
    'elwikiversity' => 'v',
    'elwikivoyage' => 'voy',
    'elwiktionary' => 'wikt',
  ),
  'emlwiki' =>
  array (
    'emlwiki' => 'w',
  ),
  'enwiki' =>
  array (
    'enwiki' => 'w',
    'enwikibooks' => 'b',
    'enwikinews' => 'n',
    'enwikiquote' => 'q',
    'enwikisource' => 's',
    'enwikiversity' => 'v',
    'enwikivoyage' => 'voy',
    'enwiktionary' => 'wikt',
  ),
  'eowiki' =>
  array (
    'eowiki' => 'w',
    'eowikibooks' => 'b',
    'eowikinews' => 'n',
    'eowikiquote' => 'q',
    'eowikisource' => 's',
    'eowiktionary' => 'wikt',
  ),
  'eswiki' =>
  array (
    'eswiki' => 'w',
    'eswikibooks' => 'b',
    'eswikinews' => 'n',
    'eswikiquote' => 'q',
    'eswikisource' => 's',
    'eswikiversity' => 'v',
    'eswikivoyage' => 'voy',
    'eswiktionary' => 'wikt',
  ),
  'etwiki' =>
  array (
    'etwiki' => 'w',
    'etwikibooks' => 'b',
    'etwikiquote' => 'q',
    'etwikisource' => 's',
    'etwiktionary' => 'wikt',
  ),
  'euwiki' =>
  array (
    'euwiki' => 'w',
    'euwikibooks' => 'b',
    'euwikiquote' => 'q',
    'euwiktionary' => 'wikt',
  ),
  'extwiki' =>
  array (
    'extwiki' => 'w',
  ),
  'fawiki' =>
  array (
    'fawiki' => 'w',
    'fawikibooks' => 'b',
    'fawikinews' => 'n',
    'fawikiquote' => 'q',
    'fawikisource' => 's',
    'fawikivoyage' => 'voy',
    'fawiktionary' => 'wikt',
  ),
  'ffwiki' =>
  array (
    'ffwiki' => 'w',
  ),
  'fiu_vrowiki' =>
  array (
    'fiu_vrowiki' => 'w',
  ),
  'fiwiki' =>
  array (
    'fiwiki' => 'w',
    'fiwikibooks' => 'b',
    'fiwikinews' => 'n',
    'fiwikiquote' => 'q',
    'fiwikisource' => 's',
    'fiwikiversity' => 'v',
    'fiwiktionary' => 'wikt',
  ),
  'fjwiki' =>
  array (
    'fjwiki' => 'w',
    'fjwiktionary' => 'wikt',
  ),
  'fowiki' =>
  array (
    'fowiki' => 'w',
    'fowikisource' => 's',
    'fowiktionary' => 'wikt',
  ),
  'frpwiki' =>
  array (
    'frpwiki' => 'w',
  ),
  'frrwiki' =>
  array (
    'frrwiki' => 'w',
  ),
  'frwiki' =>
  array (
    'frwiki' => 'w',
    'frwikibooks' => 'b',
    'frwikinews' => 'n',
    'frwikiquote' => 'q',
    'frwikisource' => 's',
    'frwikiversity' => 'v',
    'frwikivoyage' => 'voy',
    'frwiktionary' => 'wikt',
  ),
  'furwiki' =>
  array (
    'furwiki' => 'w',
  ),
  'fywiki' =>
  array (
    'fywiki' => 'w',
    'fywikibooks' => 'b',
    'fywiktionary' => 'wikt',
  ),
  'gagwiki' =>
  array (
    'gagwiki' => 'w',
  ),
  'ganwiki' =>
  array (
    'ganwiki' => 'w',
  ),
  'gawiki' =>
  array (
    'gawiki' => 'w',
    'gawiktionary' => 'wikt',
  ),
  'gdwiki' =>
  array (
    'gdwiki' => 'w',
    'gdwiktionary' => 'wikt',
  ),
  'glkwiki' =>
  array (
    'glkwiki' => 'w',
  ),
  'glwiki' =>
  array (
    'glwiki' => 'w',
    'glwikibooks' => 'b',
    'glwikiquote' => 'q',
    'glwikisource' => 's',
    'glwiktionary' => 'wikt',
  ),
  'gnwiki' =>
  array (
    'gnwiki' => 'w',
    'gnwiktionary' => 'wikt',
  ),
  'gomwiki' =>
  array (
    'gomwiki' => 'w',
  ),
  'gotwiki' =>
  array (
    'gotwiki' => 'w',
  ),
  'guwiki' =>
  array (
    'guwiki' => 'w',
    'guwikiquote' => 'q',
    'guwikisource' => 's',
    'guwiktionary' => 'wikt',
  ),
  'gvwiki' =>
  array (
    'gvwiki' => 'w',
    'gvwiktionary' => 'wikt',
  ),
  'hakwiki' =>
  array (
    'hakwiki' => 'w',
  ),
  'hawiki' =>
  array (
    'hawiki' => 'w',
    'hawiktionary' => 'wikt',
  ),
  'hawwiki' =>
  array (
    'hawwiki' => 'w',
  ),
  'hewiki' =>
  array (
    'hewiki' => 'w',
    'hewikibooks' => 'b',
    'hewikinews' => 'n',
    'hewikiquote' => 'q',
    'hewikisource' => 's',
    'hewikivoyage' => 'voy',
    'hewiktionary' => 'wikt',
  ),
  'hifwiki' =>
  array (
    'hifwiki' => 'w',
  ),
  'hiwiki' =>
  array (
    'hiwiki' => 'w',
    'hiwikibooks' => 'b',
    'hiwikiquote' => 'q',
    'hiwiktionary' => 'wikt',
  ),
  'hrwiki' =>
  array (
    'hrwiki' => 'w',
    'hrwikibooks' => 'b',
    'hrwikiquote' => 'q',
    'hrwikisource' => 's',
    'hrwiktionary' => 'wikt',
  ),
  'hsbwiki' =>
  array (
    'hsbwiki' => 'w',
    'hsbwiktionary' => 'wikt',
  ),
  'htwiki' =>
  array (
    'htwiki' => 'w',
  ),
  'huwiki' =>
  array (
    'huwiki' => 'w',
    'huwikibooks' => 'b',
    'huwikiquote' => 'q',
    'huwikisource' => 's',
    'huwiktionary' => 'wikt',
  ),
  'hywiki' =>
  array (
    'hywiki' => 'w',
    'hywikibooks' => 'b',
    'hywikiquote' => 'q',
    'hywikisource' => 's',
    'hywiktionary' => 'wikt',
  ),
  'iawiki' =>
  array (
    'iawiki' => 'w',
    'iawikibooks' => 'b',
    'iawiktionary' => 'wikt',
  ),
  'idwiki' =>
  array (
    'idwiki' => 'w',
    'idwikibooks' => 'b',
    'idwikiquote' => 'q',
    'idwikisource' => 's',
    'idwiktionary' => 'wikt',
  ),
  'iewiki' =>
  array (
    'iewiki' => 'w',
    'iewiktionary' => 'wikt',
  ),
  'igwiki' =>
  array (
    'igwiki' => 'w',
  ),
  'ikwiki' =>
  array (
    'ikwiki' => 'w',
  ),
  'ilowiki' =>
  array (
    'ilowiki' => 'w',
  ),
  'iowiki' =>
  array (
    'iowiki' => 'w',
    'iowiktionary' => 'wikt',
  ),
  'iswiki' =>
  array (
    'iswiki' => 'w',
    'iswikibooks' => 'b',
    'iswikiquote' => 'q',
    'iswikisource' => 's',
    'iswiktionary' => 'wikt',
  ),
  'itwiki' =>
  array (
    'itwiki' => 'w',
    'itwikibooks' => 'b',
    'itwikinews' => 'n',
    'itwikiquote' => 'q',
    'itwikisource' => 's',
    'itwikiversity' => 'v',
    'itwikivoyage' => 'voy',
    'itwiktionary' => 'wikt',
  ),
  'iuwiki' =>
  array (
    'iuwiki' => 'w',
    'iuwiktionary' => 'wikt',
  ),
  'jamwiki' =>
  array (
    'jamwiki' => 'w',
  ),
  'jawiki' =>
  array (
    'jawiki' => 'w',
    'jawikibooks' => 'b',
    'jawikinews' => 'n',
    'jawikiquote' => 'q',
    'jawikisource' => 's',
    'jawikiversity' => 'v',
    'jawiktionary' => 'wikt',
  ),
  'jbowiki' =>
  array (
    'jbowiki' => 'w',
    'jbowiktionary' => 'wikt',
  ),
  'jvwiki' =>
  array (
    'jvwiki' => 'w',
    'jvwiktionary' => 'wikt',
  ),
  'kaawiki' =>
  array (
    'kaawiki' => 'w',
  ),
  'kabwiki' =>
  array (
    'kabwiki' => 'w',
  ),
  'kawiki' =>
  array (
    'kawiki' => 'w',
    'kawikibooks' => 'b',
    'kawikiquote' => 'q',
    'kawiktionary' => 'wikt',
  ),
  'kbdwiki' =>
  array (
    'kbdwiki' => 'w',
  ),
  'kgwiki' =>
  array (
    'kgwiki' => 'w',
  ),
  'kiwiki' =>
  array (
    'kiwiki' => 'w',
  ),
  'kkwiki' =>
  array (
    'kkwiki' => 'w',
    'kkwikibooks' => 'b',
    'kkwiktionary' => 'wikt',
  ),
  'klwiki' =>
  array (
    'klwiki' => 'w',
    'klwiktionary' => 'wikt',
  ),
  'kmwiki' =>
  array (
    'kmwiki' => 'w',
    'kmwikibooks' => 'b',
    'kmwiktionary' => 'wikt',
  ),
  'knwiki' =>
  array (
    'knwiki' => 'w',
    'knwikiquote' => 'q',
    'knwikisource' => 's',
    'knwiktionary' => 'wikt',
  ),
  'koiwiki' =>
  array (
    'koiwiki' => 'w',
  ),
  'kowiki' =>
  array (
    'kowiki' => 'w',
    'kowikibooks' => 'b',
    'kowikinews' => 'n',
    'kowikiquote' => 'q',
    'kowikisource' => 's',
    'kowikiversity' => 'v',
    'kowiktionary' => 'wikt',
  ),
  'krcwiki' =>
  array (
    'krcwiki' => 'w',
  ),
  'kshwiki' =>
  array (
    'kshwiki' => 'w',
  ),
  'kswiki' =>
  array (
    'kswiki' => 'w',
    'kswiktionary' => 'wikt',
  ),
  'kuwiki' =>
  array (
    'kuwiki' => 'w',
    'kuwikibooks' => 'b',
    'kuwikiquote' => 'q',
    'kuwiktionary' => 'wikt',
  ),
  'kvwiki' =>
  array (
    'kvwiki' => 'w',
  ),
  'kwwiki' =>
  array (
    'kwwiki' => 'w',
    'kwwiktionary' => 'wikt',
  ),
  'kywiki' =>
  array (
    'kywiki' => 'w',
    'kywikibooks' => 'b',
    'kywikiquote' => 'q',
    'kywiktionary' => 'wikt',
  ),
  'ladwiki' =>
  array (
    'ladwiki' => 'w',
  ),
  'lawiki' =>
  array (
    'lawiki' => 'w',
    'lawikibooks' => 'b',
    'lawikiquote' => 'q',
    'lawikisource' => 's',
    'lawiktionary' => 'wikt',
  ),
  'lbewiki' =>
  array (
    'lbewiki' => 'w',
  ),
  'lbwiki' =>
  array (
    'lbwiki' => 'w',
    'lbwiktionary' => 'wikt',
  ),
  'lezwiki' =>
  array (
    'lezwiki' => 'w',
  ),
  'lgwiki' =>
  array (
    'lgwiki' => 'w',
  ),
  'lijwiki' =>
  array (
    'lijwiki' => 'w',
  ),
  'liwiki' =>
  array (
    'liwiki' => 'w',
    'liwikibooks' => 'b',
    'liwikiquote' => 'q',
    'liwikisource' => 's',
    'liwiktionary' => 'wikt',
  ),
  'lmowiki' =>
  array (
    'lmowiki' => 'w',
  ),
  'lnwiki' =>
  array (
    'lnwiki' => 'w',
    'lnwiktionary' => 'wikt',
  ),
  'lowiki' =>
  array (
    'lowiki' => 'w',
    'lowiktionary' => 'wikt',
  ),
  'lrcwiki' =>
  array (
    'lrcwiki' => 'w',
  ),
  'ltgwiki' =>
  array (
    'ltgwiki' => 'w',
  ),
  'ltwiki' =>
  array (
    'ltwiki' => 'w',
    'ltwikibooks' => 'b',
    'ltwikiquote' => 'q',
    'ltwikisource' => 's',
    'ltwiktionary' => 'wikt',
  ),
  'lvwiki' =>
  array (
    'lvwiki' => 'w',
    'lvwiktionary' => 'wikt',
  ),
  'maiwiki' =>
  array (
    'maiwiki' => 'w',
  ),
  'map_bmswiki' =>
  array (
    'map_bmswiki' => 'w',
  ),
  'mdfwiki' =>
  array (
    'mdfwiki' => 'w',
  ),
  'mgwiki' =>
  array (
    'mgwiki' => 'w',
    'mgwikibooks' => 'b',
    'mgwiktionary' => 'wikt',
  ),
  'mhrwiki' =>
  array (
    'mhrwiki' => 'w',
  ),
  'minwiki' =>
  array (
    'minwiki' => 'w',
  ),
  'miwiki' =>
  array (
    'miwiki' => 'w',
    'miwiktionary' => 'wikt',
  ),
  'mkwiki' =>
  array (
    'mkwiki' => 'w',
    'mkwikibooks' => 'b',
    'mkwikisource' => 's',
    'mkwiktionary' => 'wikt',
  ),
  'mlwiki' =>
  array (
    'mlwiki' => 'w',
    'mlwikibooks' => 'b',
    'mlwikiquote' => 'q',
    'mlwikisource' => 's',
    'mlwiktionary' => 'wikt',
  ),
  'mnwiki' =>
  array (
    'mnwiki' => 'w',
    'mnwiktionary' => 'wikt',
  ),
  'mrjwiki' =>
  array (
    'mrjwiki' => 'w',
  ),
  'mrwiki' =>
  array (
    'mrwiki' => 'w',
    'mrwikibooks' => 'b',
    'mrwikiquote' => 'q',
    'mrwikisource' => 's',
    'mrwiktionary' => 'wikt',
  ),
  'mswiki' =>
  array (
    'mswiki' => 'w',
    'mswikibooks' => 'b',
    'mswiktionary' => 'wikt',
  ),
  'mtwiki' =>
  array (
    'mtwiki' => 'w',
    'mtwiktionary' => 'wikt',
  ),
  'mwlwiki' =>
  array (
    'mwlwiki' => 'w',
  ),
  'myvwiki' =>
  array (
    'myvwiki' => 'w',
  ),
  'mywiki' =>
  array (
    'mywiki' => 'w',
    'mywiktionary' => 'wikt',
  ),
  'mznwiki' =>
  array (
    'mznwiki' => 'w',
  ),
  'nahwiki' =>
  array (
    'nahwiki' => 'w',
    'nahwiktionary' => 'wikt',
  ),
  'napwiki' =>
  array (
    'napwiki' => 'w',
  ),
  'nawiki' =>
  array (
    'nawiki' => 'w',
    'nawiktionary' => 'wikt',
  ),
  'nds_nlwiki' =>
  array (
    'nds_nlwiki' => 'w',
  ),
  'ndswiki' =>
  array (
    'ndswiki' => 'w',
    'ndswiktionary' => 'wikt',
  ),
  'newiki' =>
  array (
    'newiki' => 'w',
    'newikibooks' => 'b',
    'newiktionary' => 'wikt',
  ),
  'newwiki' =>
  array (
    'newwiki' => 'w',
  ),
  'nlwiki' =>
  array (
    'nlwiki' => 'w',
    'nlwikibooks' => 'b',
    'nlwikiquote' => 'q',
    'nlwikisource' => 's',
    'nlwikivoyage' => 'voy',
    'nlwiktionary' => 'wikt',
  ),
  'nnwiki' =>
  array (
    'nnwiki' => 'w',
    'nnwikiquote' => 'q',
    'nnwiktionary' => 'wikt',
  ),
  'novwiki' =>
  array (
    'novwiki' => 'w',
  ),
  'nowiki' =>
  array (
    'nowiki' => 'w',
    'nowikibooks' => 'b',
    'nowikinews' => 'n',
    'nowikiquote' => 'q',
    'nowikisource' => 's',
    'nowiktionary' => 'wikt',
  ),
  'nrmwiki' =>
  array (
    'nrmwiki' => 'w',
  ),
  'nsowiki' =>
  array (
    'nsowiki' => 'w',
  ),
  'nvwiki' =>
  array (
    'nvwiki' => 'w',
  ),
  'nywiki' =>
  array (
    'nywiki' => 'w',
  ),
  'ocwiki' =>
  array (
    'ocwiki' => 'w',
    'ocwikibooks' => 'b',
    'ocwiktionary' => 'wikt',
  ),
  'olowiki' =>
  array (
    'olowiki' => 'w',
  ),
  'omwiki' =>
  array (
    'omwiki' => 'w',
    'omwiktionary' => 'wikt',
  ),
  'orwiki' =>
  array (
    'orwiki' => 'w',
    'orwikisource' => 's',
    'orwiktionary' => 'wikt',
  ),
  'oswiki' =>
  array (
    'oswiki' => 'w',
  ),
  'pagwiki' =>
  array (
    'pagwiki' => 'w',
  ),
  'pamwiki' =>
  array (
    'pamwiki' => 'w',
  ),
  'papwiki' =>
  array (
    'papwiki' => 'w',
  ),
  'pawiki' =>
  array (
    'pawiki' => 'w',
    'pawikibooks' => 'b',
    'pawiktionary' => 'wikt',
  ),
  'pcdwiki' =>
  array (
    'pcdwiki' => 'w',
  ),
  'pdcwiki' =>
  array (
    'pdcwiki' => 'w',
  ),
  'pflwiki' =>
  array (
    'pflwiki' => 'w',
  ),
  'pihwiki' =>
  array (
    'pihwiki' => 'w',
  ),
  'piwiki' =>
  array (
    'piwiki' => 'w',
  ),
  'plwiki' =>
  array (
    'plwiki' => 'w',
    'plwikibooks' => 'b',
    'plwikinews' => 'n',
    'plwikiquote' => 'q',
    'plwikisource' => 's',
    'plwikivoyage' => 'voy',
    'plwiktionary' => 'wikt',
  ),
  'pmswiki' =>
  array (
    'pmswiki' => 'w',
  ),
  'pnbwiki' =>
  array (
    'pnbwiki' => 'w',
    'pnbwiktionary' => 'wikt',
  ),
  'pntwiki' =>
  array (
    'pntwiki' => 'w',
  ),
  'pswiki' =>
  array (
    'pswiki' => 'w',
    'pswiktionary' => 'wikt',
  ),
  'ptwiki' =>
  array (
    'ptwiki' => 'w',
    'ptwikibooks' => 'b',
    'ptwikinews' => 'n',
    'ptwikiquote' => 'q',
    'ptwikisource' => 's',
    'ptwikiversity' => 'v',
    'ptwikivoyage' => 'voy',
    'ptwiktionary' => 'wikt',
  ),
  'quwiki' =>
  array (
    'quwiki' => 'w',
    'quwiktionary' => 'wikt',
  ),
  'rmwiki' =>
  array (
    'rmwiki' => 'w',
  ),
  'rmywiki' =>
  array (
    'rmywiki' => 'w',
  ),
  'rnwiki' =>
  array (
    'rnwiki' => 'w',
  ),
  'roa_rupwiki' =>
  array (
    'roa_rupwiki' => 'w',
    'roa_rupwiktionary' => 'wikt',
  ),
  'roa_tarawiki' =>
  array (
    'roa_tarawiki' => 'w',
  ),
  'rowiki' =>
  array (
    'rowiki' => 'w',
    'rowikibooks' => 'b',
    'rowikinews' => 'n',
    'rowikiquote' => 'q',
    'rowikisource' => 's',
    'rowikivoyage' => 'voy',
    'rowiktionary' => 'wikt',
  ),
  'ruewiki' =>
  array (
    'ruewiki' => 'w',
  ),
  'ruwiki' =>
  array (
    'ruwiki' => 'w',
    'ruwikibooks' => 'b',
    'ruwikinews' => 'n',
    'ruwikiquote' => 'q',
    'ruwikisource' => 's',
    'ruwikiversity' => 'v',
    'ruwikivoyage' => 'voy',
    'ruwiktionary' => 'wikt',
  ),
  'rwwiki' =>
  array (
    'rwwiki' => 'w',
    'rwwiktionary' => 'wikt',
  ),
  'sahwiki' =>
  array (
    'sahwiki' => 'w',
    'sahwikisource' => 's',
  ),
  'sawiki' =>
  array (
    'sawiki' => 'w',
    'sawikibooks' => 'b',
    'sawikiquote' => 'q',
    'sawikisource' => 's',
    'sawiktionary' => 'wikt',
  ),
  'scnwiki' =>
  array (
    'scnwiki' => 'w',
    'scnwiktionary' => 'wikt',
  ),
  'scowiki' =>
  array (
    'scowiki' => 'w',
  ),
  'scwiki' =>
  array (
    'scwiki' => 'w',
  ),
  'sdwiki' =>
  array (
    'sdwiki' => 'w',
    'sdwiktionary' => 'wikt',
  ),
  'sewiki' =>
  array (
    'sewiki' => 'w',
  ),
  'sgwiki' =>
  array (
    'sgwiki' => 'w',
    'sgwiktionary' => 'wikt',
  ),
  'shwiki' =>
  array (
    'shwiki' => 'w',
    'shwiktionary' => 'wikt',
  ),
  'simplewiki' =>
  array (
    'simplewiki' => 'w',
    'simplewiktionary' => 'wikt',
  ),
  'siwiki' =>
  array (
    'siwiki' => 'w',
    'siwikibooks' => 'b',
    'siwiktionary' => 'wikt',
  ),
  'skwiki' =>
  array (
    'skwiki' => 'w',
    'skwikibooks' => 'b',
    'skwikiquote' => 'q',
    'skwikisource' => 's',
    'skwiktionary' => 'wikt',
  ),
  'slwiki' =>
  array (
    'slwiki' => 'w',
    'slwikibooks' => 'b',
    'slwikiquote' => 'q',
    'slwikisource' => 's',
    'slwikiversity' => 'v',
    'slwiktionary' => 'wikt',
  ),
  'smwiki' =>
  array (
    'smwiki' => 'w',
    'smwiktionary' => 'wikt',
  ),
  'snwiki' =>
  array (
    'snwiki' => 'w',
  ),
  'sowiki' =>
  array (
    'sowiki' => 'w',
    'sowiktionary' => 'wikt',
  ),
  'sqwiki' =>
  array (
    'sqwiki' => 'w',
    'sqwikibooks' => 'b',
    'sqwikinews' => 'n',
    'sqwikiquote' => 'q',
    'sqwiktionary' => 'wikt',
  ),
  'srnwiki' =>
  array (
    'srnwiki' => 'w',
  ),
  'srwiki' =>
  array (
    'srwiki' => 'w',
    'srwikibooks' => 'b',
    'srwikinews' => 'n',
    'srwikiquote' => 'q',
    'srwikisource' => 's',
    'srwiktionary' => 'wikt',
  ),
  'sswiki' =>
  array (
    'sswiki' => 'w',
    'sswiktionary' => 'wikt',
  ),
  'stqwiki' =>
  array (
    'stqwiki' => 'w',
  ),
  'stwiki' =>
  array (
    'stwiki' => 'w',
    'stwiktionary' => 'wikt',
  ),
  'suwiki' =>
  array (
    'suwiki' => 'w',
    'suwikiquote' => 'q',
    'suwiktionary' => 'wikt',
  ),
  'svwiki' =>
  array (
    'svwiki' => 'w',
    'svwikibooks' => 'b',
    'svwikinews' => 'n',
    'svwikiquote' => 'q',
    'svwikisource' => 's',
    'svwikiversity' => 'v',
    'svwikivoyage' => 'voy',
    'svwiktionary' => 'wikt',
  ),
  'swwiki' =>
  array (
    'swwiki' => 'w',
    'swwiktionary' => 'wikt',
  ),
  'szlwiki' =>
  array (
    'szlwiki' => 'w',
  ),
  'tawiki' =>
  array (
    'tawiki' => 'w',
    'tawikibooks' => 'b',
    'tawikinews' => 'n',
    'tawikiquote' => 'q',
    'tawikisource' => 's',
    'tawiktionary' => 'wikt',
  ),
  'tcywiki' =>
  array (
    'tcywiki' => 'w',
  ),
  'tetwiki' =>
  array (
    'tetwiki' => 'w',
  ),
  'tewiki' =>
  array (
    'tewiki' => 'w',
    'tewikibooks' => 'b',
    'tewikiquote' => 'q',
    'tewikisource' => 's',
    'tewiktionary' => 'wikt',
  ),
  'tgwiki' =>
  array (
    'tgwiki' => 'w',
    'tgwikibooks' => 'b',
    'tgwiktionary' => 'wikt',
  ),
  'thwiki' =>
  array (
    'thwiki' => 'w',
    'thwikibooks' => 'b',
    'thwikiquote' => 'q',
    'thwikisource' => 's',
    'thwiktionary' => 'wikt',
  ),
  'tiwiki' =>
  array (
    'tiwiki' => 'w',
    'tiwiktionary' => 'wikt',
  ),
  'tkwiki' =>
  array (
    'tkwiki' => 'w',
    'tkwiktionary' => 'wikt',
  ),
  'tlwiki' =>
  array (
    'tlwiki' => 'w',
    'tlwikibooks' => 'b',
    'tlwiktionary' => 'wikt',
  ),
  'tnwiki' =>
  array (
    'tnwiki' => 'w',
    'tnwiktionary' => 'wikt',
  ),
  'towiki' =>
  array (
    'towiki' => 'w',
  ),
  'tpiwiki' =>
  array (
    'tpiwiki' => 'w',
    'tpiwiktionary' => 'wikt',
  ),
  'trwiki' =>
  array (
    'trwiki' => 'w',
    'trwikibooks' => 'b',
    'trwikinews' => 'n',
    'trwikiquote' => 'q',
    'trwikisource' => 's',
    'trwiktionary' => 'wikt',
  ),
  'tswiki' =>
  array (
    'tswiki' => 'w',
    'tswiktionary' => 'wikt',
  ),
  'ttwiki' =>
  array (
    'ttwiki' => 'w',
    'ttwikibooks' => 'b',
    'ttwiktionary' => 'wikt',
  ),
  'tumwiki' =>
  array (
    'tumwiki' => 'w',
  ),
  'twwiki' =>
  array (
    'twwiki' => 'w',
  ),
  'tyvwiki' =>
  array (
    'tyvwiki' => 'w',
  ),
  'tywiki' =>
  array (
    'tywiki' => 'w',
  ),
  'udmwiki' =>
  array (
    'udmwiki' => 'w',
  ),
  'ugwiki' =>
  array (
    'ugwiki' => 'w',
    'ugwiktionary' => 'wikt',
  ),
  'ukwiki' =>
  array (
    'ukwiki' => 'w',
    'ukwikibooks' => 'b',
    'ukwikinews' => 'n',
    'ukwikiquote' => 'q',
    'ukwikisource' => 's',
    'ukwikivoyage' => 'voy',
    'ukwiktionary' => 'wikt',
  ),
  'urwiki' =>
  array (
    'urwiki' => 'w',
    'urwikibooks' => 'b',
    'urwikiquote' => 'q',
    'urwiktionary' => 'wikt',
  ),
  'uzwiki' =>
  array (
    'uzwiki' => 'w',
    'uzwikiquote' => 'q',
    'uzwiktionary' => 'wikt',
  ),
  'vecwiki' =>
  array (
    'vecwiki' => 'w',
    'vecwikisource' => 's',
    'vecwiktionary' => 'wikt',
  ),
  'vepwiki' =>
  array (
    'vepwiki' => 'w',
  ),
  'vewiki' =>
  array (
    'vewiki' => 'w',
  ),
  'viwiki' =>
  array (
    'viwiki' => 'w',
    'viwikibooks' => 'b',
    'viwikiquote' => 'q',
    'viwikisource' => 's',
    'viwikivoyage' => 'voy',
    'viwiktionary' => 'wikt',
  ),
  'vlswiki' =>
  array (
    'vlswiki' => 'w',
  ),
  'vowiki' =>
  array (
    'vowiki' => 'w',
    'vowiktionary' => 'wikt',
  ),
  'warwiki' =>
  array (
    'warwiki' => 'w',
  ),
  'wawiki' =>
  array (
    'wawiki' => 'w',
    'wawiktionary' => 'wikt',
  ),
  'wowiki' =>
  array (
    'wowiki' => 'w',
    'wowikiquote' => 'q',
    'wowiktionary' => 'wikt',
  ),
  'wuuwiki' =>
  array (
    'wuuwiki' => 'w',
  ),
  'xalwiki' =>
  array (
    'xalwiki' => 'w',
  ),
  'xhwiki' =>
  array (
    'xhwiki' => 'w',
  ),
  'xmfwiki' =>
  array (
    'xmfwiki' => 'w',
  ),
  'yiwiki' =>
  array (
    'yiwiki' => 'w',
    'yiwikisource' => 's',
    'yiwiktionary' => 'wikt',
  ),
  'yowiki' =>
  array (
    'yowiki' => 'w',
  ),
  'zawiki' =>
  array (
    'zawiki' => 'w',
  ),
  'zeawiki' =>
  array (
    'zeawiki' => 'w',
  ),
  'zh_classicalwiki' =>
  array (
    'zh_classicalwiki' => 'w',
  ),
  'zh_min_nanwiki' =>
  array (
    'zh_min_nanwiki' => 'w',
    'zh_min_nanwikisource' => 's',
    'zh_min_nanwiktionary' => 'wikt',
  ),
  'zh_yuewiki' =>
  array (
    'zh_yuewiki' => 'w',
  ),
  'zhwiki' =>
  array (
    'zhwiki' => 'w',
    'zhwikibooks' => 'b',
    'zhwikinews' => 'n',
    'zhwikiquote' => 'q',
    'zhwikisource' => 's',
    'zhwikivoyage' => 'voy',
    'zhwiktionary' => 'wikt',
  ),
  'zuwiki' =>
  array (
    'zuwiki' => 'w',
    'zuwiktionary' => 'wikt',
  ),
);
