<?php
# WARNING: This file is publicly viewable on the web. Do not put private data here.

/**
 * The InterwikiSorting mediawiki extension is controlled via this array through
 * $wgInterwikiSortingInterwikiSortOrders.
 * Please read the docs: https://www.mediawiki.org/wiki/Extension:InterwikiSorting#Configuration
 * Orders originate from: https://meta.wikimedia.org/wiki/Interwiki_sorting_order?oldid=3362178
 */

// phpcs:disable MediaWiki.WhiteSpace.SpaceBeforeSingleLineComment.NewLineComment
return [
	// by language name (converted to Latin script), e.g. 'id' as 'Indonesia, bahasa'
	'alphabetic' => [
		'ace', // Acèh = Aceh
		'ady', // Адыгабзэ = Adygabee
		'kbd', // Адыгэбзэ = Adygebee
		'ang', // Ænglisc = Aenglisc
		'af', // Afrikaans = Afrikaans
		'ak', // Akan = Akan
		'als', // Alemannisch = Alemannisch
		'alt', // Алтай тил = Altay til
		'am', // አማርኛ = Amarenna
		'smn', // Anarâškielâ = Anaraskiela
		'anp', // अंगिका = Amgika
		'ab', // Аԥсшәа = Apshea
		'ar', // العربية = Arabiyyah, al-
		'an', // Aragonés = Aragones
		'arc', // ܐܪܡܝܐ = Aramaya
		'hyw', // Արեւմտահայերէն = Arevmdahayeren
		'roa-rup', // Armãneashti = Armaneashti
		'frp', // Arpetan = Arpetan
		'as', // অসমীয়া = Asamiya
		'ast', // Asturianu = Asturianu
		'atj', // Atikamekw = Atikamekw
		'awa', // अवधी = Avadhi
		'gn', // Avañe'ẽ = Avanee
		'av', // Авар = Avar
		'ay', // Aymar aru = Aymar aru
		'az', // Azərbaycanca = Azarbaycanca
		'azb', // تۆرکجه = Azarbaycan dili
		'bdr', // Bajau Sama = Bajau sama
		'ban', // Basa Bali = Bali, basa
		'bm', // Bamanankan = Bamanankan
		'bn', // বাংলা = Bangla
		'bjn', // Banjar = Banjar
		'zh-min-nan', // 閩南語 / Bân-lâm-gí = Banlamgi
		'nan', // 閩南語 / Bân-lâm-gí = Banlamgi
		'map-bms', // Basa Banyumasan = Banyumasan, basa
		'ba', // Башҡортса = Bashkortsa
		'btm', // Batak Mandailing = Batak mandailing
		'bbc', // Batak Toba = Batak toba
		'be', // Беларуская = Belaruskaya
		'be-x-old', // Беларуская (тарашкевіца) = Belaruskaya, tarashkevitsa
		'bew', // Betawi = Betawi
		'bh', // भोजपुरी = Bhojpur
		'bcl', // Bikol Central = Bikol central
		'bi', // Bislama = Bislama
		'bpy', // বিষ্ণুপ্রিয়া মণিপুরী = Bisnupriya monipuri
		'bar', // Boarisch = Boarisch
		'bo', // བོད་ཡིག = Bod yig
		'bs', // Bosanski = Bosanski
		'br', // Brezhoneg = Brezhoneg
		'bxr', // Буряад = Budyaad
		'bg', // Български = Bugarski
		'ca', // Català = Catala
		'ceb', // Cebuano = Cebuano
		'cs', // Čeština = Cestina
		'cho', // Chahta anumpa = Chahta anumpa
		'ch', // Chamoru = Chamoru
		'cbk-zam', // Chavacano de Zamboanga = Chavacano de Zamboanga
		'cv', // Чӑвашла = Chavashla
		'ny', // Chi-Chewa = Chichewa
		'sn', // ChiShona = Chishona
		'tum', // ChiTumbuka = Chitumbuka
		'co', // Corsu = Corsu
		'cy', // Cymraeg = Cymraeg
		'dga', // Dagaare = Dagaare
		'dag', // Dagbanli = Dagbanli
		'da', // Dansk = Dansk
		'ary', // الدارجة = Darija, ad-
		'se', // Davvisámegiella = Davvisamegiella
		'pdc', // Deitsch = Deitsch
		'de', // Deutsch = Deutsch
		'nv', // Diné bizaad = Dine bizaad
		'dv', // ދިވެހިބަސް = Divehi
		'dsb', // Dolnoserbski = Dolnoserbski
		'dty', // डोटेली = Dotyali
		'dz', // ཇོང་ཁ = Dzongkha
		'mh', // Ebon = Ebon
		'et', // Eesti = Eesti
		'el', // Ελληνικά = Ellinika
		'eml', // Emiliàn e rumagnòl = Emilian e rumagnol
		'en', // English = English
		'myv', // Эрзянь = Erzyan
		'es', // Español = Espanol
		'eo', // Esperanto = Esperanto
		'ext', // Estremeñu = Estremenu
		'eu', // Euskara = Euskara
		'ee', // Eʋegbe = Evegbe
		'gur', // Farefare = Farefare
		'fa', // فارسی = Farsi
		'hif', // Fiji Hindi = Fiji Hindi
		'fon', // Fɔ̀ngbè = Fongbe
		'fo', // Føroyskt = Foroyskt
		'fr', // Français = Francais
		'fy', // Frysk = Frysk
		'ff', // Fulfulde = Fulfulde
		'fur', // Furlan = Furlan
		'ga', // Gaeilge = Gaeilge
		'gv', // Gaelg = Gaelg
		'gag', // Gagauz = Gagauz
		'gd', // Gàidhlig = Gaidhlig
		'gl', // Galego = Galego
		'inh', // ГӀалгӀай = Ghalghaj
		'gpe', // Ghanaian Pidgin = Ghanaian Pidgin
		'gan', // 贛語 = Ganyu
		'ki', // Gĩkũyũ = Gikuyu
		'glk', // گیلکی = Gilaki
		'gom', // गोंयची कोंकणी / Gõychi Konknni = Goychi konknni
		'gu', // ગુજરાતી = Gujrat
		'guw', // Gungbe = Gungbe
		'got', // 𐌲𐌿𐍄𐌹𐍃𐌺 = Gutisk
		'hak', // 客家語 / Hak-kâ-ngî = Hakkangi
		'ko', // 한국어 = Hangugeo
		'ha', // Hausa = Hausa
		'haw', // Hawaiʻi = Hawaii
		'hy', // Հայերեն = Hayeren
		'hi', // हिन्दी = Hindi
		'ho', // Hiri Motu = Hiri motu
		'hsb', // Hornjoserbsce = Hornjoserbsce
		'hr', // Hrvatski = Hrvatski
		'gor', // Bahasa Hulontalo = Hulontalo, Bahasa
		'iba', // Jaku Iban = Iban, jaku
		'io', // Ido = Ido
		'igl', // Igala = Igala
		'ig', // Igbo = Igbo
		'rw', // Ikinyarwanda = Ikinyarwanda
		'rn', // Ikirundi = Ikirundi
		'ilo', // Ilokano = Ilokano
		'id', // Bahasa Indonesia = Indonesia, Bahasa
		'ia', // Interlingua = Interlingua
		'ie', // Interlingue = Interlingue
		'iu', // ᐃᓄᒃᑎᑐᑦ / inuktitut = Inuktitut
		'ik', // Iñupiatun = Inupiatun
		'os', // Ирон = Iron
		'nr', // IsiNdebele seSewula = Isindbele sesewula
		'xh', // IsiXhosa = Isixhosa
		'zu', // IsiZulu = Isizulu
		'is', // Íslenska = Islenska
		'it', // Italiano = Italiano
		'he', // עברית = Ivrit
		'jv', // Jawa = Jawa
		'kaj', // Jju = Jju
		'kbp', // Kabɩyɛ = Kabiye
		'dtp', // Kadazandusun = Kadazandusun
		'kl', // Kalaallisut = Kalaallisut
		'kn', // ಕನ್ನಡ = Kannada
		'kr', // kanuri = Kanuri
		'pam', // Kapampangan = Kapampangan
		'krc', // Къарачай-малкъар = Karachay-malkar
		'ka', // ქართული = Kartuli
		'ks', // کٲشُر = Kasur
		'csb', // Kaszëbsczi = Kaszebsczi
		'kw', // Kernowek = Kernowek
		'xal', // Хальмг = Khalmg
		'km', // ភាសាខ្មែរ = Khmae
		'sw', // Kiswahili = Kiswahili
		'kv', // Коми = Komi
		'kg', // Kongo = Kongo
		'avk', // Kotava = Kotava
		'ht', // Kreyòl ayisyen = Kreyol ayisyen
		'gcr', // Kriyòl gwiyannen = Kriyol gwiyannen
		'kge', // Kumoring = Kumoring
		'ku', // Kurdî = Kurdi
		'ckb', // کوردی = Kurdi
		'kus', // Kʋsaal = Kusaal
		'kj', // Kwanyama = Kwanyama
		'ky', // Кыргызча = Kyrgyzcha
		'mrj', // Кырык мары = Kyryk mary
		'lld', // Ladin = Ladin
		'lad', // Ladino = Ladino
		'lbe', // Лакку = Lakku
		'lo', // ລາວ = Lao
		'ltg', // Latgaļu = Latgalu
		'la', // Latina = Latina
		'lv', // Latviešu = Latviesu
		'lb', // Lëtzebuergesch = Letzebuergesch
		'lez', // Лезги = Lezgi
		'lt', // Lietuvių = Lietuviu
		'nia', // Li Niha = Li niha
		'lij', // Ligure = Ligure
		'li', // Limburgs = Limburgs
		'ln', // Lingála = Lingala
		'lfn', // Lingua Franca Nova = Lingua Franca Nova
		'olo', // Livvinkarjala = Livvinkarjala
		'jbo', // La .lojban = lojban, la
		'lg', // Luganda = Luganda
		'lrc', // لۊری شومالی = Luri
		'lmo', // Lombard = Lombard
		'mad', // Madhurâ = Madhura
		'hu', // Magyar = Magyar
		'mai', // मैथिली = Maithili
		'mk', // Македонски = Makedonski
		'mg', // Malagasy = Malagasy
		'ml', // മലയാളം = Malayalam
		'mt', // Malti = Malti
		'mi', // Māori = Maori
		'mr', // मराठी = Marathi
		'xmf', // მარგალური = Margaluri
		'arz', // مصرى = Masri
		'mzn', // مازِرونی = Mazeruni
		'ms', // Bahasa Melayu = Melayu, bahasa
		'mni', // ꯃꯤꯇꯩ ꯂꯣꯟ = Meitei
		'fat', // Mfantse = Mfantse
		'min', // Minangkabau = Minangkabau
		'cdo', // 閩東語 / Mìng-dĕ̤ng-ngṳ̄ = Mingde ngngu
		'mwl', // Mirandés = Mirandes
		'mdf', // Мокшень = Mokshen
		'mo', // молдовеняскэ = Moldovenyaske
		'mnw', // ဘာသာမန် = Mon, bhasa
		'mn', // Монгол = Mongol
		'mos', // Moore = Moore
		'my', // မြန်မာဘာသာ = Mranma
		'mus', // Mvskoke = Mvskoke
		'nah', // Nāhuatl = Nahuatl
		'pcm', // Naijá = Naija
		'na', // Dorerin Naoero = Naoero, dorerin
		'nap', // Napulitano = Napulitano
		'fj', // Na Vosa Vakaviti = Na vosa vakaviti
		'ppl', // Nawat = Nawat
		'nl', // Nederlands = Nederlands
		'nds-nl', // Nedersaksies = Nedersaksies
		'cr', // Nēhiyawēwin / ᓀᐦᐃᔭᐍᐏᐣ = Nehiyawewin
		'ne', // नेपाली = Nepali
		'new', // नेपाल भाषा = Nepala bhasa
		'ja', // 日本語 = Nihongo
		'nqo', // ߒߞߏ = Nko
		'ce', // Нохчийн = Nokhchiyn
		'frr', // Nordfriisk = Nordfriisk
		'pih', // Norfuk / Pitkern = Norfuk pitkern
		'no', // Norsk = Norsk
		'nb', // Norsk bokmål = Norsk bokmal
		'nn', // Norsk nynorsk = Norsk nynorsk
		'nrm', // Nouormand = Nouormand
		'nov', // Novial = Novial
		'ii', // ꆇꉙ = Nuosuhxop
		'nup', // Nupe = Nupe
		'ann', // Obolo = Obolo
		'oc', // Occitan = Occitan
		'mhr', // Олык марий = Olyk mariy
		'or', // ଓଡ଼ିଆ = Oria
		'om', // Oromoo = Oromoo
		'ng', // Oshiwambo = Oshiwambo
		'hz', // Otsiherero = Otsiherero
		'uz', // Oʻzbekcha / ўзбекча = Ozbekcha
		'pi', // पालि = Pali
		'pfl', // Pälzisch = Palzisch
		'pag', // Pangasinan = Pangasinan
		'ami', // Pangcah = Pangcah
		'pa', // ਪੰਜਾਬੀ = Panjabi
		'pnb', // پنجابی = Panjabi
		'blk', // ပအိုဝ်ႏဘာႏသာႏ = Paophasa
		'pap', // Papiamentu = Papiamentu
		'jam', // Patois = Patois
		'ps', // پښتو = Paxto
		'koi', // Перем коми = Perem komi
		'pcd', // Picard = Picard
		'pms', // Piemontèis = Piemonteis
		'pwn', // Pinayuanan = Pinayuanan
		'tpi', // Tok Pisin = Pisin, tok
		'nds', // Plattdüütsch = Plattduutsch
		'pl', // Polski = Polski
		'pnt', // Ποντιακά = Pontiaka
		'pt', // Português = Portugues
		'aa', // Qafár af = Qafar af
		'kaa', // Qaraqalpaqsha = Qaraqalpaqsha
		'kk', // Қазақша = Qazaqsa
		'crh', // Qırımtatarca = Qirimtatarca
		'rki', // ရခိုင် = Rahkuing
		'ty', // Reo tahiti = Reo tahiti
		'ksh', // Ripoarisch = Ripoarisch
		'ro', // Română = Romana
		'rmy', // Romani čhib = Romani chib
		'rm', // Rumantsch = Rumantsch
		'qu', // Runa Simi = Runa simi
		'rue', // Русиньскый = Rusinskyy
		'rsk', // Руски = Ruski
		'ru', // Русский = Russkiy
		'sah', // Саха тыла = Sakha tyla
		'szy', // Sakizaya = Sakizaya
		'sm', // Gagana Samoa = Samoa, gagana
		'sa', // संस्कृतम् = Samskrta
		'sg', // Sängö = Sango
		'sat', // ᱥᱟᱱᱛᱟᱲᱤ = Santari
		'skr', // سرائیکی = Saraiki
		'sc', // Sardu = Sardu
		'sco', // Scots = Scots
		'trv', // Seediq = Seediq
		'stq', // Seeltersk = Seeltersk
		'st', // Sesotho = Sesotho
		'nso', // Sesotho sa Leboa = Sesotho sa leboa
		'tn', // Setswana = Setswana
		'sq', // Shqip = Shqip
		'scn', // Sicilianu = Sicilianu
		'syl', // ꠍꠤꠟꠐꠤ = Siloti
		'si', // සිංහල = Simhala
		'simple', // Simple English = Simple English
		'sd', // سنڌي = Sindhi
		'ss', // SiSwati = Siswati
		'sk', // Slovenčina = Slovencina
		'sl', // Slovenščina = Slovenscina
		'cu', // Словѣньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ = Slovyansk
		'szl', // Ślůnski = Slunski
		'so', // Soomaaliga = Soomaaliga
		'srn', // Sranantongo = Sranantongo
		'sr', // Српски / srpski = Srpski
		'sh', // Srpskohrvatski / српскохрватски = Srpskohrvatski
		'su', // Sunda = Sunda
		'fi', // Suomi = Suomi
		'sv', // Svenska = Svenska
		'shy', // Tacawit = Tacawit
		'shi', // Taclḥit = Taclhit
		'tl', // Tagalog = Tagalog
		'ta', // தமிழ் = Tamil
		'tdd', // ᥖᥭᥰ ᥖᥬᥲ ᥑᥨᥒᥰ = Tai tau hong
		'zgh', // ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ = Tamazight tanawayt
		'kab', // Taqbaylit = Taqbaylit
		'roa-tara', // Tarandíne = Tarandíne
		'tt', // Татарча / tatarça = Tatarca
		'th', // ไทย = Tai
		'shn', // တႆး = Tai
		'tay', // Tayal = Tayal
		'tig', // ትግሬ = Tegre
		'ti', // ትግርኛ = Tegrenna
		'te', // తెలుగు = Telugu
		'tet', // Tetun = Tetun
		'din', // Thuɔŋjäŋ = Thuonjan
		'tg', // Тоҷикӣ = Tochiky
		'tok', // toki pona = Toki pona
		'tly', // Tolışi = Tolisi
		'to', // Lea faka-Tonga = Tonga, Lea faka-
		'chr', // ᏣᎳᎩ = Tsalagi
		'chy', // Tsetsêhestâhese = Tsetsehestahese
		've', // Tshivenda = Tshivenda
		'tcy', // ತುಳು = Tulu
		'tr', // Türkçe = Turkce
		'tk', // Türkmençe = Turkmence
		'tw', // Twi = Twi
		'kcg', // Tyap = Tyap
		'tyv', // Тыва дыл = Tyva dyl
		'udm', // Удмурт = Udmurt
		'bug', // Basa Ugi = Ugi, basa
		'uk', // Українська = Ukrainska
		'ur', // اردو = Urdu
		'ug', // ئۇيغۇرچە / Uyghurche = Uyghurche
		'za', // Vahcuengh = Vahcuengh
		'vec', // Vèneto = Veneto
		'vep', // Vepsän kel’ = Vepsan kel
		'vi', // Tiếng Việt = Viet, tieng
		'vo', // Volapük = Volapuk
		'fiu-vro', // Võro = Voro
		'wa', // Walon = Walon
		'guc', // Wayuunaiki = Wayuunaiki
		'zh-classical', // 文言 = Wenyan
		'vls', // West-Vlams = West-vlams
		'war', // Winaray = Winaray
		'wo', // Wolof = Wolof
		'wuu', // 吴语 = Wuyu
		'ts', // Xitsonga = Xitsonga
		'knc', // Yerwa Kanuri = Yerwa kanuri
		'yi', // ייִדיש = Yidish
		'yo', // Yorùbá = Yoruba
		'yue', // 粵語 = Yueyu
		'zh-yue', // 粵語 = Yueyu
		'diq', // Zazaki = Zazaki
		'zea', // Zeêuws = Zeeuws
		'bat-smg', // Žemaitėška = Zemaiteska
		'zh', // 中文 = Zhongwen
	],
	// by first word, e.g. 'id' as 'bahasa Indonesia'
	'alphabetic_revised' => [
		'ace', // Acèh = Aceh
		'ary', // الدارجة = Addarija
		'ady', // Адыгабзэ = Adygabee
		'kbd', // Адыгэбзэ = Adygebee
		'ang', // Ænglisc = Aenglisc
		'af', // Afrikaans = Afrikaans
		'ak', // Akan = Akan
		'ar', // العربية = Alarabiyyah
		'als', // Alemannisch = Alemannisch
		'alt', // Алтай тил = Altay til
		'am', // አማርኛ = Amarenna
		'smn', // Anarâškielâ = Anaraskiela
		'anp', // अंगिका = Amgika
		'ab', // Аԥсшәа = Apshea
		'an', // Aragonés = Aragones
		'arc', // ܐܪܡܝܐ = Aramaya
		'hyw', // Արեւմտահայերէն = Arevmdahayeren
		'roa-rup', // Armãneashti = Armaneashti
		'frp', // Arpetan = Arpetan
		'as', // অসমীয়া = Asamiya
		'ast', // Asturianu = Asturianu
		'atj', // Atikamekw = Atikamekw
		'awa', // अवधी = Avadhi
		'gn', // Avañe'ẽ = Avanee
		'av', // Авар = Avar
		'ay', // Aymar aru = Aymar aru
		'az', // Azərbaycanca = Azarbaycanca
		'azb', // تۆرکجه = Azarbaycan dili
		'gor', // Bahasa Hulontalo = Bahasa Hulontalo
		'id', // Bahasa Indonesia = Bahasa Indonesia
		'ms', // Bahasa Melayu = Bahasa Melayu
		'bdr', // Bajau Sama = Bajau sama
		'bm', // Bamanankan = Bamanankan
		'bn', // বাংলা = Bangla
		'bjn', // Banjar = Banjar
		'zh-min-nan', // 閩南語 / Bân-lâm-gí = Banlamgi
		'nan', // 閩南語 / Bân-lâm-gí = Banlamgi
		'map-bms', // Basa Banyumasan = Basa Banyumasan
		'ban', // Basa Bali = Basa Bali
		'bug', // Basa Ugi = Basa ugi
		'ba', // Башҡортса = Bashkortsa
		'btm', // Batak Mandailing = Batak mandailing
		'bbc', // Batak Toba = Batak toba
		'be', // Беларуская = Belaruskaya
		'be-x-old', // Беларуская (тарашкевіца) = Belaruskaya, tarashkevitsa
		'bew', // Betawi = Betawi
		'mnw', // ဘာသာမန် = Bhasa mon
		'bh', // भोजपुरी = Bhojpur
		'bcl', // Bikol Central = Bikol central
		'bi', // Bislama = Bislama
		'bpy', // বিষ্ণুপ্রিয়া মণিপুরী = Bisnupriya monipuri
		'bar', // Boarisch = Boarisch
		'bo', // བོད་ཡིག = Bod yig
		'bs', // Bosanski = Bosanski
		'br', // Brezhoneg = Brezhoneg
		'bxr', // Буряад = Budyaad
		'bg', // Български = Bugarski
		'ca', // Català = Catala
		'ceb', // Cebuano = Cebuano
		'cs', // Čeština = Cestina
		'cho', // Chahta anumpa = Chahta anumpa
		'ch', // Chamoru = Chamoru
		'cbk-zam', // Chavacano de Zamboanga = Chavacano de Zamboanga
		'cv', // Чӑвашла = Chavashla
		'ny', // Chi-Chewa = Chichewa
		'sn', // ChiShona = Chishona
		'tum', // ChiTumbuka = Chitumbuka
		'co', // Corsu = Corsu
		'cy', // Cymraeg = Cymraeg
		'dga', // Dagaare = Dagaare
		'dag', // Dagbanli = Dagbanli
		'da', // Dansk = Dansk
		'se', // Davvisámegiella = Davvisamegiella
		'pdc', // Deitsch = Deitsch
		'de', // Deutsch = Deutsch
		'nv', // Diné bizaad = Dine bizaad
		'dv', // ދިވެހިބަސް = Divehi
		'dsb', // Dolnoserbski = Dolnoserbski
		'na', // Dorerin Naoero = Dorerin naoero
		'dty', // डोटेली = Dotyali
		'dz', // ཇོང་ཁ = Dzongkha
		'mh', // Ebon = Ebon
		'et', // Eesti = Eesti
		'el', // Ελληνικά = Ellinika
		'eml', // Emiliàn e rumagnòl = Emilian e rumagnol
		'en', // English = English
		'myv', // Эрзянь = Erzyan
		'es', // Español = Espanol
		'eo', // Esperanto = Esperanto
		'ext', // Estremeñu = Estremenu
		'eu', // Euskara = Euskara
		'ee', // Eʋegbe = Evegbe
		'gur', // Farefare = Farefare
		'fa', // فارسی = Farsi
		'hif', // Fiji Hindi = Fiji Hindi
		'fon', // Fɔ̀ngbè = Fongbe
		'fo', // Føroyskt = Foroyskt
		'fr', // Français = Francais
		'fy', // Frysk = Frysk
		'ff', // Fulfulde = Fulfulde
		'fur', // Furlan = Furlan
		'ga', // Gaeilge = Gaeilge
		'gv', // Gaelg = Gaelg
		'sm', // Gagana Samoa = Gagana samoa
		'gag', // Gagauz = Gagauz
		'gd', // Gàidhlig = Gaidhlig
		'gl', // Galego = Galego
		'inh', // ГӀалгӀай = Ghalghaj
		'gpe', // Ghanaian Pidgin = Ghanaian Pidgin
		'gan', // 贛語 = Ganyu
		'ki', // Gĩkũyũ = Gikuyu
		'glk', // گیلکی = Gilaki
		'gom', // गोंयची कोंकणी / Gõychi Konknni = Goychi konknni
		'gu', // ગુજરાતી = Gujrat
		'guw', // Gungbe = Gungbe
		'got', // 𐌲𐌿𐍄𐌹𐍃𐌺 = Gutisk
		'hak', // 客家語 / Hak-kâ-ngî = Hakkangi
		'ko', // 한국어 = Hangugeo
		'ha', // Hausa = Hausa
		'haw', // Hawaiʻi = Hawaii
		'hy', // Հայերեն = Hayeren
		'hi', // हिन्दी = Hindi
		'ho', // Hiri Motu = Hiri motu
		'hsb', // Hornjoserbsce = Hornjoserbsce
		'hr', // Hrvatski = Hrvatski
		'io', // Ido = Ido
		'igl', // Igala = Igala
		'ig', // Igbo = Igbo
		'rw', // Ikinyarwanda = Ikinyarwanda
		'rn', // Ikirundi = Ikirundi
		'ilo', // Ilokano = Ilokano
		'ia', // Interlingua = Interlingua
		'ie', // Interlingue = Interlingue
		'iu', // ᐃᓄᒃᑎᑐᑦ / inuktitut = Inuktitut
		'ik', // Iñupiatun = Inupiatun
		'os', // Ирон = Iron
		'nr', // IsiNdebele seSewula = Isindbele sesewula
		'xh', // IsiXhosa = Isixhosa
		'zu', // IsiZulu = Isizulu
		'is', // Íslenska = Islenska
		'it', // Italiano = Italiano
		'he', // עברית = Ivrit
		'iba', // Jaku Iban = Jaku Iban
		'jv', // Jawa = Jawa
		'kaj', // Jju = Jju
		'kbp', // Kabɩyɛ = Kabiye
		'dtp', // Kadazandusun = Kadazandusun
		'kl', // Kalaallisut = Kalaallisut
		'kn', // ಕನ್ನಡ = Kannada
		'kr', // kanuri = Kanuri
		'pam', // Kapampangan = Kapampangan
		'krc', // Къарачай-малкъар = Karachaymalkar
		'ka', // ქართული = Kartuli
		'ks', // کٲشُر = Kasur
		'csb', // Kaszëbsczi = Kaszebsczi
		'kw', // Kernowek = Kernowek
		'xal', // Хальмг = Khalmg
		'km', // ភាសាខ្មែរ = Khmae
		'sw', // Kiswahili = Kiswahili
		'kv', // Коми = Komi
		'kg', // Kongo = Kongo
		'avk', // Kotava = Kotava
		'ht', // Kreyòl ayisyen = Kreyol ayisyen
		'gcr', // Kriyòl gwiyannen = Kriyol gwiyannen
		'kge', // Kumoring = Kumoring
		'ku', // Kurdî = Kurdi
		'ckb', // کوردی = Kurdi
		'kus', // Kʋsaal = Kusaal
		'kj', // Kwanyama = Kwanyama
		'ky', // Кыргызча = Kyrgyzcha
		'mrj', // Кырык мары = Kyryk mary
		'lld', // Ladin = Ladin
		'lad', // Ladino = Ladino
		'lbe', // Лакку = Lakku
		'jbo', // La .lojban = La lojban
		'lo', // ລາວ = Lao
		'ltg', // Latgaļu = Latgalu
		'la', // Latina = Latina
		'lv', // Latviešu = Latviesu
		'to', // Lea faka-Tonga = Lea faka tonga-
		'lb', // Lëtzebuergesch = Letzebuergesch
		'lez', // Лезги = Lezgi
		'lt', // Lietuvių = Lietuviu
		'nia', // Li Niha = Li niha
		'lij', // Ligure = Ligure
		'li', // Limburgs = Limburgs
		'ln', // Lingála = Lingala
		'lfn', // Lingua Franca Nova = Lingua Franca Nova
		'olo', // Livvinkarjala = Livvinkarjala
		'lg', // Luganda = Luganda
		'lrc', // لۊری شومالی = Luri
		'lmo', // Lombard = Lombard
		'mad', // Madhurâ = Madhura
		'hu', // Magyar = Magyar
		'mai', // मैथिली = Maithili
		'mk', // Македонски = Makedonski
		'mg', // Malagasy = Malagasy
		'ml', // മലയാളം = Malayalam
		'mt', // Malti = Malti
		'mi', // Māori = Maori
		'mr', // मराठी = Marathi
		'xmf', // მარგალური = Margaluri
		'arz', // مصرى = Masri
		'mzn', // مازِرونی = Mazeruni
		'mni', // ꯃꯤꯇꯩ ꯂꯣꯟ = Meitei
		'fat', // Mfantse = Mfantse
		'min', // Minangkabau = Minangkabau
		'cdo', // 閩東語 / Mìng-dĕ̤ng-ngṳ̄ = Mingde ngngu
		'mwl', // Mirandés = Mirandes
		'mdf', // Мокшень = Mokshen
		'mo', // молдовеняскэ = Moldovenyaske
		'mn', // Монгол = Mongol
		'mos', // Moore = Moore
		'my', // မြန်မာဘာသာ = Mranma
		'mus', // Mvskoke = Mvskoke
		'nah', // Nāhuatl = Nahuatl
		'pcm', // Naijá = Naija
		'nap', // Napulitano = Napulitano
		'fj', // Na Vosa Vakaviti = Na vosa vakaviti
		'ppl', // Nawat = Nawat
		'nl', // Nederlands = Nederlands
		'nds-nl', // Nedersaksies = Nedersaksies
		'cr', // Nēhiyawēwin / ᓀᐦᐃᔭᐍᐏᐣ = Nehiyawewin
		'ne', // नेपाली = Nepali
		'new', // नेपाल भाषा = Nepala bhasa
		'ja', // 日本語 = Nihongo
		'nqo', // ߒߞߏ = Nko
		'ce', // Нохчийн = Nokhchiyn
		'frr', // Nordfriisk = Nordfriisk
		'pih', // Norfuk / Pitkern = Norfuk pitkern
		'no', // Norsk = Norsk
		'nb', // Norsk bokmål = Norsk bokmal
		'nn', // Norsk nynorsk = Norsk nynorsk
		'nrm', // Nouormand = Nouormand
		'nov', // Novial = Novial
		'ii', // ꆇꉙ = Nuosuhxop
		'nup', // Nupe = Nupe
		'ann', // Obolo = Obolo
		'oc', // Occitan = Occitan
		'mhr', // Олык марий = Olyk mariy
		'or', // ଓଡ଼ିଆ = Oria
		'om', // Oromoo = Oromoo
		'ng', // Oshiwambo = Oshiwambo
		'hz', // Otsiherero = Otsiherero
		'uz', // Oʻzbekcha / ўзбекча = Ozbekcha
		'pi', // पालि = Pali
		'pfl', // Pälzisch = Palzisch
		'pag', // Pangasinan = Pangasinan
		'ami', // Pangcah = Pangcah
		'pa', // ਪੰਜਾਬੀ = Panjabi
		'pnb', // پنجابی = Panjabi
		'blk', // ပအိုဝ်ႏဘာႏသာႏ = Paophasa
		'pap', // Papiamentu = Papiamentu
		'jam', // Patois = Patois
		'ps', // پښتو = Paxto
		'koi', // Перем коми = Perem komi
		'pcd', // Picard = Picard
		'pms', // Piemontèis = Piemonteis
		'pwn', // Pinayuanan = Pinayuanan
		'nds', // Plattdüütsch = Plattduutsch
		'pl', // Polski = Polski
		'tpi', // Tok Pisin = Tok pisin
		'tok', // toki pona = Toki pona
		'pnt', // Ποντιακά = Pontiaka
		'pt', // Português = Portugues
		'aa', // Qafár af = Qafar af
		'kaa', // Qaraqalpaqsha = Qaraqalpaqsha
		'kk', // Қазақша = Qazaqsa
		'crh', // Qırımtatarca = Qirimtatarca
		'rki', // ရခိုင် = Rahkuing
		'ty', // Reo tahiti = Reo tahiti
		'ksh', // Ripoarisch = Ripoarisch
		'ro', // Română = Romana
		'rmy', // Romani čhib = Romani chib
		'rm', // Rumantsch = Rumantsch
		'qu', // Runa Simi = Runa simi
		'rue', // Русиньскый = Rusinskyy
		'rsk', // Руски = Ruski
		'ru', // Русский = Russkiy
		'sah', // Саха тыла = Sakha tyla
		'szy', // Sakizaya = Sakizaya
		'sa', // संस्कृतम् = Samskrta
		'sg', // Sängö = Sango
		'sat', // ᱥᱟᱱᱛᱟᱲᱤ = Santari
		'skr', // سرائیکی = Saraiki
		'sc', // Sardu = Sardu
		'sco', // Scots = Scots
		'trv', // Seediq = Seediq
		'stq', // Seeltersk = Seeltersk
		'st', // Sesotho = Sesotho
		'nso', // Sesotho sa Leboa = Sesotho sa leboa
		'tn', // Setswana = Setswana
		'sq', // Shqip = Shqip
		'scn', // Sicilianu = Sicilianu
		'syl', // ꠍꠤꠟꠐꠤ = Siloti
		'si', // සිංහල = Simhala
		'simple', // Simple English = Simple English
		'sd', // سنڌي = Sindhi
		'ss', // SiSwati = Siswati
		'sk', // Slovenčina = Slovencina
		'sl', // Slovenščina = Slovenscina
		'cu', // Словѣньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ = Slovyansk
		'szl', // Ślůnski = Slunski
		'so', // Soomaaliga = Soomaaliga
		'srn', // Sranantongo = Sranantongo
		'sr', // Српски / srpski = Srpski
		'sh', // Srpskohrvatski / српскохрватски = Srpskohrvatski
		'su', // Sunda = Sunda
		'fi', // Suomi = Suomi
		'sv', // Svenska = Svenska
		'shy', // Tacawit = Tacawit
		'shi', // Taclḥit = Taclhit
		'tl', // Tagalog = Tagalog
		'ta', // தமிழ் = Tamil
		'tdd', // ᥖᥭᥰ ᥖᥬᥲ ᥑᥨᥒᥰ = Tai tau hong
		'zgh', // ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ = Tamazight tanawayt
		'kab', // Taqbaylit = Taqbaylit
		'roa-tara', // Tarandíne = Tarandíne
		'tt', // Татарча / tatarça = Tatarca
		'th', // ไทย = Tai
		'shn', // တႆး = Tai
		'tay', // Tayal = Tayal
		'tig', // ትግሬ = Tegre
		'ti', // ትግርኛ = Tegrenna
		'te', // తెలుగు = Telugu
		'tet', // Tetun = Tetun
		'din', // Thuɔŋjäŋ = Thuonjan
		'vi', // Tiếng Việt = Tieng viet
		'tg', // Тоҷикӣ = Tochiky
		'tly', // Tolışi = Tolisi
		'chr', // ᏣᎳᎩ = Tsalagi
		'chy', // Tsetsêhestâhese = Tsetsehestahese
		've', // Tshivenda = Tshivenda
		'tcy', // ತುಳು = Tulu
		'tr', // Türkçe = Turkce
		'tk', // Türkmençe = Turkmence
		'tw', // Twi = Twi
		'kcg', // Tyap = Tyap
		'tyv', // Тыва дыл = Tyva dyl
		'udm', // Удмурт = Udmurt
		'uk', // Українська = Ukrainska
		'ur', // اردو = Urdu
		'ug', // ئۇيغۇرچە / Uyghurche = Uyghurche
		'za', // Vahcuengh = Vahcuengh
		'vec', // Vèneto = Veneto
		'vep', // Vepsän kel’ = Vepsan kel
		'vo', // Volapük = Volapuk
		'fiu-vro', // Võro = Voro
		'wa', // Walon = Walon
		'guc', // Wayuunaiki = Wayuunaiki
		'zh-classical', // 文言 = Wenyan
		'vls', // West-Vlams = West-vlams
		'war', // Winaray = Winaray
		'wo', // Wolof = Wolof
		'wuu', // 吴语 = Wuyu
		'ts', // Xitsonga = Xitsonga
		'knc', // Yerwa Kanuri = Yerwa kanuri
		'yi', // ייִדיש = Yidish
		'yo', // Yorùbá = Yoruba
		'yue', // 粵語 = Yueyu
		'zh-yue', // 粵語 = Yueyu
		'diq', // Zazaki = Zazaki
		'zea', // Zeêuws = Zeeuws
		'bat-smg', // Žemaitėška = Zemaiteska
		'zh', // 中文 = Zhongwen
	],
	// by first word, non-Cyrillic/non-Roman/non-Greek name by language code
	'alphabetic_sr' => [
		'ace', // Acèh = Aceh
		'ady', // Адыгабзэ = Adygabee
		'kbd', // Адыгэбзэ = Adygebee
		'ang', // Ænglisc = Aenglisc
		'af', // Afrikaans = Afrikaans
		'ak', // Akan = Akan
		'als', // Alemannisch = Alemannisch
		'alt', // Алтай тил = Altay til
		'am', // አማርኛ = Amarenna
		'smn', // Anarâškielâ = Anaraskiela
		'anp', // अंगिका = Amgika
		'ab', // Аԥсшәа = Apshea
		'ar', // العربية = Alarabiyyah
		'an', // Aragonés = Aragones
		'arc', // ܐܪܡܝܐ = Aramaya
		'roa-rup', // Armãneashti = Armaneashti
		'frp', // Arpetan = Arpetan
		'ary', // الدارجة = Addarija
		'arz', // مصرى = Masri
		'as', // অসমীয়া = Asamiya
		'ast', // Asturianu = Asturianu
		'atj', // Atikamekw = Atikamekw
		'gn', // Avañe'ẽ = Avanee
		'av', // Авар = Avar
		'awa', // अवधी = Avadhi
		'ay', // Aymar aru = Aymar aru
		'az', // Azərbaycanca = Azarbaycanca
		'azb', // تۆرکجه = Azarbaycan dili
		'gor', // Bahasa Hulontalo = Bahasa Hulontalo
		'id', // Bahasa Indonesia = Bahasa Indonesia
		'ms', // Bahasa Melayu = Bahasa Melayu
		'bdr', // Bajau Sama = Bajau sama
		'bm', // Bamanankan = Bamanankan
		'bjn', // Banjar = Banjar
		'map-bms', // Basa Banyumasan = Basa Banyumasan
		'ban', // Basa Bali = Basa Bali
		'bug', // Basa Ugi = Basa ugi
		'ba', // Башҡортса = Bashkortsa
		'btm', // Batak Mandailing = Batak mandailing
		'bbc', // Batak Toba = Batak toba
		'be', // Беларуская = Belaruskaya
		'be-x-old', // Беларуская (тарашкевіца) = Belaruskaya, tarashkevitsa
		'bew', // Betawi = Betawi
		'bh', // भोजपुरी = Bhojpur
		'bcl', // Bikol Central = Bikol central
		'bi', // Bislama = Bislama
		'bn', // বাংলা = Bangla
		'bar', // Boarisch = Boarisch
		'bo', // བོད་ཡིག = Bod yig
		'bs', // Bosanski = Bosanski
		'bpy', // বিষ্ণুপ্রিয়া মণিপুরী = Bisnupriya monipuri
		'br', // Brezhoneg = Brezhoneg
		'bxr', // Буряад = Budyaad
		'bg', // Български = Bugarski
		'ca', // Català = Catala
		'cdo', // 閩東語 / Mìng-dĕ̤ng-ngṳ̄ = Mingde ngngu
		'ceb', // Cebuano = Cebuano
		'cs', // Čeština = Cestina
		'cho', // Chahta anumpa = Chahta anumpa
		'ch', // Chamoru = Chamoru
		'cbk-zam', // Chavacano de Zamboanga = Chavacano de Zamboanga
		'cv', // Чӑвашла = Chavashla
		'ny', // Chi-Chewa = Chichewa
		'sn', // ChiShona = Chishona
		'tum', // ChiTumbuka = Chitumbuka
		'chr', // ᏣᎳᎩ = Tsalagi
		'ckb', // کوردی = Kurdi
		'co', // Corsu = Corsu
		'cy', // Cymraeg = Cymraeg
		'dga', // Dagaare = Dagaare
		'dag', // Dagbanli = Dagbanli
		'da', // Dansk = Dansk
		'se', // Davvisámegiella = Davvisamegiella
		'pdc', // Deitsch = Deitsch
		'de', // Deutsch = Deutsch
		'nv', // Diné bizaad = Dine bizaad
		'dsb', // Dolnoserbski = Dolnoserbski
		'na', // Dorerin Naoero = Dorerin naoero
		'dty', // डोटेली = Dotyali
		'dv', // ދިވެހިބަސް = Divehi
		'dz', // ཇོང་ཁ = Dzongkha
		'mh', // Ebon = Ebon
		'et', // Eesti = Eesti
		'el', // Ελληνικά = Ellinika
		'eml', // Emiliàn e rumagnòl = Emilian e rumagnol
		'en', // English = English
		'myv', // Эрзянь = Erzyan
		'es', // Español = Espanol
		'eo', // Esperanto = Esperanto
		'ext', // Estremeñu = Estremenu
		'eu', // Euskara = Euskara
		'ee', // Eʋegbe = Evegbe
		'fa', // فارسی = Farsi
		'gur', // Farefare = Farefare
		'hif', // Fiji Hindi = Fiji Hindi
		'fon', // Fɔ̀ngbè = Fongbe
		'fo', // Føroyskt = Foroyskt
		'fr', // Français = Francais
		'fy', // Frysk = Frysk
		'ff', // Fulfulde = Fulfulde
		'fur', // Furlan = Furlan
		'ga', // Gaeilge = Gaeilge
		'gv', // Gaelg = Gaelg
		'sm', // Gagana Samoa = Gagana samoa
		'gag', // Gagauz = Gagauz
		'gd', // Gàidhlig = Gaidhlig
		'gl', // Galego = Galego
		'gan', // 贛語 = Ganyu
		'inh', // ГӀалгӀай = Ghalghaj
		'gpe', // Ghanaian Pidgin = Ghanaian Pidgin
		'ki', // Gĩkũyũ = Gikuyu
		'glk', // گیلکی = Gilaki
		'gom', // गोंयची कोंकणी / Gõychi Konknni = Goychi konknni
		'gu', // ગુજરાતી = Gujrat
		'guw', // Gungbe = Gungbe
		'got', // 𐌲𐌿𐍄𐌹𐍃𐌺 = Gutisk
		'hak', // 客家語 / Hak-kâ-ngî = Hakkangi
		'ha', // Hausa = Hausa
		'haw', // Hawaiʻi = Hawaii
		'he', // עברית = Ivrit
		'hi', // हिन्दी = Hindi
		'ho', // Hiri Motu = Hiri motu
		'hsb', // Hornjoserbsce = Hornjoserbsce
		'hr', // Hrvatski = Hrvatski
		'hy', // Հայերեն = Hayeren
		'hyw', // Արեւմտահայերէն = Arevmdahayeren
		'io', // Ido = Ido
		'igl', // Igala = Igala
		'ig', // Igbo = Igbo
		'ii', // ꆇꉙ = Nuosuhxop
		'rw', // Ikinyarwanda = Ikinyarwanda
		'rn', // Ikirundi = Ikirundi
		'ilo', // Ilokano = Ilokano
		'ia', // Interlingua = Interlingua
		'ie', // Interlingue = Interlingue
		'iu', // ᐃᓄᒃᑎᑐᑦ / inuktitut = Inuktitut
		'ik', // Iñupiatun = Inupiatun
		'os', // Ирон = Iron
		'nr', // IsiNdebele seSewula = Isindbele sesewula
		'xh', // IsiXhosa = Isixhosa
		'zu', // IsiZulu = Isizulu
		'is', // Íslenska = Islenska
		'it', // Italiano = Italiano
		'ja', // 日本語 = Nihongo
		'iba', // Jaku Iban = Jaku Iban
		'jv', // Jawa = Jawa
		'kaj', // Jju = Jju
		'kbp', // Kabɩyɛ = Kabiye
		'ka', // ქართული = Kartuli
		'dtp', // Kadazandusun = Kadazandusun
		'kl', // Kalaallisut = Kalaallisut
		'kr', // kanuri = Kanuri
		'pam', // Kapampangan = Kapampangan
		'krc', // Къарачай-малкъар = Karachaymalkar
		'csb', // Kaszëbsczi = Kaszebsczi
		'kw', // Kernowek = Kernowek
		'xal', // Хальмг = Khalmg
		'sw', // Kiswahili = Kiswahili
		'kv', // Коми = Komi
		'km', // ភាសាខ្មែរ = Khmae
		'kn', // ಕನ್ನಡ = Kannada
		'ko', // 한국어 = Hangugeo
		'kg', // Kongo = Kongo
		'avk', // Kotava = Kotava
		'ht', // Kreyòl ayisyen = Kreyol ayisyen
		'gcr', // Kriyòl gwiyannen = Kriyol gwiyannen
		'ks', // کٲشُر = Kasur
		'kge', // Kumoring = Kumoring
		'ku', // Kurdî = Kurdi
		'kus', // Kʋsaal = Kusaal
		'kj', // Kwanyama = Kwanyama
		'ky', // Кыргызча = Kyrgyzcha
		'mrj', // Кырык мары = Kyryk mary
		'lld', // Ladin = Ladin
		'lad', // Ladino = Ladino
		'lbe', // Лакку = Lakku
		'jbo', // La .lojban = La lojban
		'ltg', // Latgaļu = Latgalu
		'la', // Latina = Latina
		'lv', // Latviešu = Latviesu
		'to', // Lea faka-Tonga = Lea faka tonga-
		'lb', // Lëtzebuergesch = Letzebuergesch
		'lez', // Лезги = Lezgi
		'lt', // Lietuvių = Lietuviu
		'nia', // Li Niha = Li niha
		'lij', // Ligure = Ligure
		'li', // Limburgs = Limburgs
		'ln', // Lingála = Lingala
		'lfn', // Lingua Franca Nova = Lingua Franca Nova
		'olo', // Livvinkarjala = Livvinkarjala
		'lrc', // لۊری شومالی = Luri
		'lg', // Luganda = Luganda
		'lo', // ລາວ = Lao
		'lmo', // Lombard = Lombard
		'mad', // Madhurâ = Madhura
		'hu', // Magyar = Magyar
		'mai', // मैथिली = Maithili
		'mk', // Македонски = Makedonski
		'mg', // Malagasy = Malagasy
		'ml', // മലയാളം = Malayalam
		'mt', // Malti = Malti
		'mi', // Māori = Maori
		'fat', // Mfantse = Mfantse
		'min', // Minangkabau = Minangkabau
		'mni', // ꯃꯤꯇꯩ ꯂꯣꯟ = Meitei
		'mnw', // ဘာသာမန် = Bhasa mon
		'mwl', // Mirandés = Mirandes
		'mdf', // Мокшень = Mokshen
		'mo', // молдовеняскэ = Moldovenyaske
		'mn', // Монгол = Mongol
		'mos', // Moore = Moore
		'mr', // मराठी = Marathi
		'my', // မြန်မာဘာသာ = Mranma
		'mus', // Mvskoke = Mvskoke
		'mzn', // مازِرونی = Mazeruni
		'nah', // Nāhuatl = Nahuatl
		'pcm', // Naijá = Naija
		'nan', // 閩南語 / Bân-lâm-gí = Banlamgi
		'nap', // Napulitano = Napulitano
		'fj', // Na Vosa Vakaviti = Na vosa vakaviti
		'ppl', // Nawat = Nawat
		'ne', // नेपाली = Nepali
		'nl', // Nederlands = Nederlands
		'nds-nl', // Nedersaksies = Nedersaksies
		'cr', // Nēhiyawēwin / ᓀᐦᐃᔭᐍᐏᐣ = Nehiyawewin
		'new', // नेपाल भाषा = Nepala bhasa
		'ce', // Нохчийн = Nokhchiyn
		'frr', // Nordfriisk = Nordfriisk
		'pih', // Norfuk / Pitkern = Norfuk pitkern
		'no', // Norsk = Norsk
		'nb', // Norsk bokmål = Norsk bokmal
		'nn', // Norsk nynorsk = Norsk nynorsk
		'nrm', // Nouormand = Nouormand
		'nov', // Novial = Novial
		'nqo', // ߒߞߏ = Nko
		'nup', // Nupe = Nupe
		'ann', // Obolo = Obolo
		'oc', // Occitan = Occitan
		'mhr', // Олык марий = Olyk mariy
		'or', // ଓଡ଼ିଆ = Oria
		'om', // Oromoo = Oromoo
		'ng', // Oshiwambo = Oshiwambo
		'hz', // Otsiherero = Otsiherero
		'uz', // Oʻzbekcha / ўзбекча = Ozbekcha
		'pi', // पालि = Pali
		'pfl', // Pälzisch = Palzisch
		'pag', // Pangasinan = Pangasinan
		'ami', // Pangcah = Pangcah
		'pa', // ਪੰਜਾਬੀ = Panjabi
		'pnb', // پنجابی = Panjabi
		'blk', // ပအိုဝ်ႏဘာႏသာႏ = Paophasa
		'pap', // Papiamentu = Papiamentu
		'jam', // Patois = Patois
		'ps', // پښتو = Paxto
		'koi', // Перем коми = Perem komi
		'pcd', // Picard = Picard
		'pms', // Piemontèis = Piemonteis
		'pwn', // Pinayuanan = Pinayuanan
		'nds', // Plattdüütsch = Plattduutsch
		'pl', // Polski = Polski
		'tpi', // Tok Pisin = Tok pisin
		'tok', // toki pona = Toki pona
		'pnt', // Ποντιακά = Pontiaka
		'pt', // Português = Portugues
		'aa', // Qafár af = Qafar af
		'kaa', // Qaraqalpaqsha = Qaraqalpaqsha
		'kk', // Қазақша = Qazaqsa
		'crh', // Qırımtatarca = Qirimtatarca
		'ty', // Reo tahiti = Reo tahiti
		'ksh', // Ripoarisch = Ripoarisch
		'rki', // ရခိုင် = Rahkuing
		'ro', // Română = Romana
		'rmy', // Romani čhib = Romani chib
		'rm', // Rumantsch = Rumantsch
		'qu', // Runa Simi = Runa simi
		'rue', // Русиньскый = Rusinskyy
		'rsk', // Руски = Ruski
		'ru', // Русский = Russkiy
		'sa', // संस्कृतम् = Samskrta
		'sah', // Саха тыла = Sakha tyla
		'szy', // Sakizaya = Sakizaya
		'sg', // Sängö = Sango
		'skr', // سرائیکی = Saraiki
		'sc', // Sardu = Sardu
		'sat', // ᱥᱟᱱᱛᱟᱲᱤ = Santari
		'sco', // Scots = Scots
		'sd', // سنڌي = Sindhi
		'trv', // Seediq = Seediq
		'stq', // Seeltersk = Seeltersk
		'st', // Sesotho = Sesotho
		'nso', // Sesotho sa Leboa = Sesotho sa leboa
		'tn', // Setswana = Setswana
		'shn', // တႆး = Tai
		'sq', // Shqip = Shqip
		'si', // සිංහල = Simhala
		'scn', // Sicilianu = Sicilianu
		'simple', // Simple English = Simple English
		'ss', // SiSwati = Siswati
		'sk', // Slovenčina = Slovencina
		'sl', // Slovenščina = Slovenscina
		'cu', // Словѣньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ = Slovyansk
		'szl', // Ślůnski = Slunski
		'so', // Soomaaliga = Soomaaliga
		'srn', // Sranantongo = Sranantongo
		'sr', // Српски / srpski = Srpski
		'sh', // Srpskohrvatski / српскохрватски = Srpskohrvatski
		'su', // Sunda = Sunda
		'fi', // Suomi = Suomi
		'sv', // Svenska = Svenska
		'syl', // ꠍꠤꠟꠐꠤ = Siloti
		'ta', // தமிழ் = Tamil
		'shy', // Tacawit = Tacawit
		'shi', // Taclḥit = Taclhit
		'tl', // Tagalog = Tagalog
		'kab', // Taqbaylit = Taqbaylit
		'roa-tara', // Tarandíne = Tarandíne
		'tt', // Татарча / tatarça = Tatarca
		'tay', // Tayal = Tayal
		'tdd', // ᥖᥭᥰ ᥖᥬᥲ ᥑᥨᥒᥰ = Tai tau hong
		'te', // తెలుగు = Telugu
		'tet', // Tetun = Tetun
		'th', // ไทย = Tai
		'din', // Thuɔŋjäŋ = Thuonjan
		'ti', // ትግርኛ = Tegrenna
		'vi', // Tiếng Việt = Tieng viet
		'tig', // ትግሬ = Tegre
		'tg', // Тоҷикӣ = Tochiky
		'tly', // Tolışi = Tolisi
		'chy', // Tsetsêhestâhese = Tsetsehestahese
		've', // Tshivenda = Tshivenda
		'tcy', // ತುಳು = Tulu
		'tr', // Türkçe = Turkce
		'tk', // Türkmençe = Turkmence
		'tw', // Twi = Twi
		'kcg', // Tyap = Tyap
		'tyv', // Тыва дыл = Tyva dyl
		'udm', // Удмурт = Udmurt
		'uk', // Українська = Ukrainska
		'ur', // اردو = Urdu
		'ug', // ئۇيغۇرچە / Uyghurche = Uyghurche
		'za', // Vahcuengh = Vahcuengh
		'vec', // Vèneto = Veneto
		'vep', // Vepsän kel’ = Vepsan kel
		'vo', // Volapük = Volapuk
		'fiu-vro', // Võro = Voro
		'wa', // Walon = Walon
		'guc', // Wayuunaiki = Wayuunaiki
		'vls', // West-Vlams = West-vlams
		'war', // Winaray = Winaray
		'wo', // Wolof = Wolof
		'wuu', // 吴语 = Wuyu
		'ts', // Xitsonga = Xitsonga
		'xmf', // მარგალური = Margaluri
		'knc', // Yerwa Kanuri = Yerwa kanuri
		'yi', // ייִדיש = Yidish
		'yo', // Yorùbá = Yoruba
		'yue', // 粵語 = Yueyu
		'diq', // Zazaki = Zazaki
		'zea', // Zeêuws = Zeeuws
		'bat-smg', // Žemaitėška = Zemaiteska
		'zgh', // ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ = Tamazight tanawayt
		'zh', // 中文 = Zhongwen
		'zh-classical', // 文言 = Wenyan
		'zh-min-nan', // 閩南語 / Bân-lâm-gí = Banlamgi
		'zh-yue', // 粵語 = Yueyu
	],
	// by language code, except 'y' is sorted like 'i'
	'alphabetic_fy' => [
		'aa', // Qafár af = Qafar af
		'ab', // Аԥсшәа = Apshea
		'ace', // Acèh = Aceh
		'ady', // Адыгабзэ = Adygabee
		'af', // Afrikaans = Afrikaans
		'ay', // Aymar aru = Aymar aru
		'ak', // Akan = Akan
		'als', // Alemannisch = Alemannisch
		'alt', // Алтай тил = Altay til
		'am', // አማርኛ = Amarenna
		'ami', // Pangcah = Pangcah
		'an', // Aragonés = Aragones
		'ang', // Ænglisc = Aenglisc
		'ann', // Obolo = Obolo
		'anp', // अंगिका = Amgika
		'ar', // العربية = Alarabiyyah
		'arc', // ܐܪܡܝܐ = Aramaya
		'ary', // الدارجة = Addarija
		'arz', // مصرى = Masri
		'as', // অসমীয়া = Asamiya
		'ast', // Asturianu = Asturianu
		'atj', // Atikamekw = Atikamekw
		'av', // Авар = Avar
		'avk', // Kotava = Kotava
		'awa', // अवधी = Avadhi
		'az', // Azərbaycanca = Azarbaycanca
		'azb', // تۆرکجه = Azarbaycan dili
		'ba', // Башҡортса = Bashkortsa
		'ban', // Basa Bali = Basa Bali
		'bar', // Boarisch = Boarisch
		'bat-smg', // Žemaitėška = Zemaiteska
		'bbc', // Batak Toba = Batak toba
		'bcl', // Bikol Central = Bikol central
		'bdr', // Bajau Sama = Bajau sama
		'be', // Беларуская = Belaruskaya
		'be-x-old', // Беларуская (тарашкевіца) = Belaruskaya, tarashkevitsa
		'bew', // Betawi = Betawi
		'bg', // Български = Bugarski
		'bh', // भोजपुरी = Bhojpur
		'bi', // Bislama = Bislama
		'bjn', // Banjar = Banjar
		'blk', // ပအိုဝ်ႏဘာႏသာႏ = Paophasa
		'bm', // Bamanankan = Bamanankan
		'bn', // বাংলা = Bangla
		'bo', // བོད་ཡིག = Bod yig
		'bpy', // বিষ্ণুপ্রিয়া মণিপুরী = Bisnupriya monipuri
		'br', // Brezhoneg = Brezhoneg
		'bs', // Bosanski = Bosanski
		'btm', // Batak Mandailing = Batak mandailing
		'bug', // Basa Ugi = Basa ugi
		'bxr', // Буряад = Budyaad
		'ca', // Català = Catala
		'cbk-zam', // Chavacano de Zamboanga = Chavacano de Zamboanga
		'cdo', // 閩東語 / Mìng-dĕ̤ng-ngṳ̄ = Mingde ngngu
		'ce', // Нохчийн = Nokhchiyn
		'ceb', // Cebuano = Cebuano
		'ch', // Chamoru = Chamoru
		'chy', // Tsetsêhestâhese = Tsetsehestahese
		'cho', // Chahta anumpa = Chahta anumpa
		'chr', // ᏣᎳᎩ = Tsalagi
		'cy', // Cymraeg = Cymraeg
		'ckb', // کوردی = Kurdi
		'co', // Corsu = Corsu
		'cr', // Nēhiyawēwin / ᓀᐦᐃᔭᐍᐏᐣ = Nehiyawewin
		'crh', // Qırımtatarca = Qirimtatarca
		'cs', // Čeština = Cestina
		'csb', // Kaszëbsczi = Kaszebsczi
		'cu', // Словѣньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ = Slovyansk
		'cv', // Чӑвашла = Chavashla
		'da', // Dansk = Dansk
		'dag', // Dagbanli = Dagbanli
		'de', // Deutsch = Deutsch
		'dga', // Dagaare = Dagaare
		'din', // Thuɔŋjäŋ = Thuonjan
		'diq', // Zazaki = Zazaki
		'dsb', // Dolnoserbski = Dolnoserbski
		'dty', // डोटेली = Dotyali
		'dtp', // Kadazandusun = Kadazandusun
		'dv', // ދިވެހިބަސް = Divehi
		'dz', // ཇོང་ཁ = Dzongkha
		'ee', // Eʋegbe = Evegbe
		'el', // Ελληνικά = Ellinika
		'eml', // Emiliàn e rumagnòl = Emilian e rumagnol
		'en', // English = English
		'eo', // Esperanto = Esperanto
		'es', // Español = Espanol
		'et', // Eesti = Eesti
		'eu', // Euskara = Euskara
		'ext', // Estremeñu = Estremenu
		'fa', // فارسی = Farsi
		'fat', // Mfantse = Mfantse
		'ff', // Fulfulde = Fulfulde
		'fi', // Suomi = Suomi
		'fy', // Frysk = Frysk
		'fiu-vro', // Võro = Voro
		'fj', // Na Vosa Vakaviti = Na vosa vakaviti
		'fo', // Føroyskt = Foroyskt
		'fon', // Fɔ̀ngbè = Fongbe
		'fr', // Français = Francais
		'frp', // Arpetan = Arpetan
		'frr', // Nordfriisk = Nordfriisk
		'fur', // Furlan = Furlan
		'ga', // Gaeilge = Gaeilge
		'gag', // Gagauz = Gagauz
		'gan', // 贛語 = Ganyu
		'gcr', // Kriyòl gwiyannen = Kriyol gwiyannen
		'gd', // Gàidhlig = Gaidhlig
		'gl', // Galego = Galego
		'glk', // گیلکی = Gilaki
		'gn', // Avañe'ẽ = Avanee
		'gom', // गोंयची कोंकणी / Gõychi Konknni = Goychi konknni
		'gor', // Bahasa Hulontalo = Bahasa Hulontalo
		'got', // 𐌲𐌿𐍄𐌹𐍃𐌺 = Gutisk
		'gpe', // Ghanaian Pidgin = Ghanaian Pidgin
		'gu', // ગુજરાતી = Gujrat
		'guc', // Wayuunaiki = Wayuunaiki
		'gur', // Farefare = Farefare
		'guw', // Gungbe = Gungbe
		'gv', // Gaelg = Gaelg
		'ha', // Hausa = Hausa
		'hak', // 客家語 / Hak-kâ-ngî = Hakkangi
		'haw', // Hawaiʻi = Hawaii
		'he', // עברית = Ivrit
		'hi', // हिन्दी = Hindi
		'hy', // Հայերեն = Hayeren
		'hif', // Fiji Hindi = Fiji Hindi
		'hyw', // Արեւմտահայերէն = Arevmdahayeren
		'ho', // Hiri Motu = Hiri motu
		'hr', // Hrvatski = Hrvatski
		'hsb', // Hornjoserbsce = Hornjoserbsce
		'ht', // Kreyòl ayisyen = Kreyol ayisyen
		'hu', // Magyar = Magyar
		'hz', // Otsiherero = Otsiherero
		'ia', // Interlingua = Interlingua
		'iba', // Jaku Iban = Jaku Iban
		'id', // Bahasa Indonesia = Bahasa Indonesia
		'ie', // Interlingue = Interlingue
		'ig', // Igbo = Igbo
		'igl', // Igala = Igala
		'ii', // ꆇꉙ = Nuosuhxop
		'yi', // ייִדיש = Yidish
		'ik', // Iñupiatun = Inupiatun
		'ilo', // Ilokano = Ilokano
		'inh', // ГӀалгӀай = Ghalghaj
		'io', // Ido = Ido
		'yo', // Yorùbá = Yoruba
		'is', // Íslenska = Islenska
		'it', // Italiano = Italiano
		'iu', // ᐃᓄᒃᑎᑐᑦ / inuktitut = Inuktitut
		'yue', // 粵語 = Yueyu
		'ja', // 日本語 = Nihongo
		'jam', // Patois = Patois
		'jbo', // La .lojban = La lojban
		'jv', // Jawa = Jawa
		'ka', // ქართული = Kartuli
		'kaa', // Qaraqalpaqsha = Qaraqalpaqsha
		'kab', // Taqbaylit = Taqbaylit
		'kaj', // Jju = Jju
		'kbd', // Адыгэбзэ = Adygebee
		'kbp', // Kabɩyɛ = Kabiye
		'kcg', // Tyap = Tyap
		'kg', // Kongo = Kongo
		'kge', // Kumoring = Kumoring
		'ki', // Gĩkũyũ = Gikuyu
		'ky', // Кыргызча = Kyrgyzcha
		'kj', // Kwanyama = Kwanyama
		'kk', // Қазақша = Qazaqsa
		'kl', // Kalaallisut = Kalaallisut
		'km', // ភាសាខ្មែរ = Khmae
		'kn', // ಕನ್ನಡ = Kannada
		'knc', // Yerwa Kanuri = Yerwa kanuri
		'ko', // 한국어 = Hangugeo
		'koi', // Перем коми = Perem komi
		'kr', // kanuri = Kanuri
		'krc', // Къарачай-малкъар = Karachaymalkar
		'ks', // کٲشُر = Kasur
		'ksh', // Ripoarisch = Ripoarisch
		'ku', // Kurdî = Kurdi
		'kus', // Kʋsaal = Kusaal
		'kv', // Коми = Komi
		'kw', // Kernowek = Kernowek
		'la', // Latina = Latina
		'lad', // Ladino = Ladino
		'lb', // Lëtzebuergesch = Letzebuergesch
		'lbe', // Лакку = Lakku
		'lez', // Лезги = Lezgi
		'lfn', // Lingua Franca Nova = Lingua Franca Nova
		'lg', // Luganda = Luganda
		'li', // Limburgs = Limburgs
		'lij', // Ligure = Ligure
		'lld', // Ladin = Ladin
		'lmo', // Lombard = Lombard
		'ln', // Lingála = Lingala
		'lo', // ລາວ = Lao
		'lrc', // لۊری شومالی = Luri
		'lt', // Lietuvių = Lietuviu
		'ltg', // Latgaļu = Latgalu
		'lv', // Latviešu = Latviesu
		'mad', // Madhurâ = Madhura
		'mai', // मैथिली = Maithili
		'map-bms', // Basa Banyumasan = Basa Banyumasan
		'mdf', // Мокшень = Mokshen
		'mg', // Malagasy = Malagasy
		'mh', // Ebon = Ebon
		'mhr', // Олык марий = Olyk mariy
		'mi', // Māori = Maori
		'my', // မြန်မာဘာသာ = Mranma
		'min', // Minangkabau = Minangkabau
		'myv', // Эрзянь = Erzyan
		'mk', // Македонски = Makedonski
		'ml', // മലയാളം = Malayalam
		'mn', // Монгол = Mongol
		'mni', // ꯃꯤꯇꯩ ꯂꯣꯟ = Meitei
		'mnw', // ဘာသာမန် = Bhasa mon
		'mo', // молдовеняскэ = Moldovenyaske
		'mos', // Moore = Moore
		'mr', // मराठी = Marathi
		'mrj', // Кырык мары = Kyryk mary
		'ms', // Bahasa Melayu = Bahasa Melayu
		'mt', // Malti = Malti
		'mus', // Mvskoke = Mvskoke
		'mwl', // Mirandés = Mirandes
		'mzn', // مازِرونی = Mazeruni
		'na', // Dorerin Naoero = Dorerin naoero
		'nah', // Nāhuatl = Nahuatl
		'nan', // 閩南語 / Bân-lâm-gí = Banlamgi
		'nap', // Napulitano = Napulitano
		'nb', // Norsk bokmål = Norsk bokmal
		'nds', // Plattdüütsch = Plattduutsch
		'nds-nl', // Nedersaksies = Nedersaksies
		'ne', // नेपाली = Nepali
		'new', // नेपाल भाषा = Nepala bhasa
		'ng', // Oshiwambo = Oshiwambo
		'ny', // Chi-Chewa = Chichewa
		'nia', // Li Niha = Li niha
		'nl', // Nederlands = Nederlands
		'nn', // Norsk nynorsk = Norsk nynorsk
		'no', // Norsk = Norsk
		'nov', // Novial = Novial
		'nqo', // ߒߞߏ = Nko
		'nr', // IsiNdebele seSewula = Isindbele sesewula
		'nrm', // Nouormand = Nouormand
		'nso', // Sesotho sa Leboa = Sesotho sa leboa
		'nup', // Nupe = Nupe
		'nv', // Diné bizaad = Dine bizaad
		'oc', // Occitan = Occitan
		'olo', // Livvinkarjala = Livvinkarjala
		'om', // Oromoo = Oromoo
		'or', // ଓଡ଼ିଆ = Oria
		'os', // Ирон = Iron
		'pa', // ਪੰਜਾਬੀ = Panjabi
		'pag', // Pangasinan = Pangasinan
		'pam', // Kapampangan = Kapampangan
		'pap', // Papiamentu = Papiamentu
		'pcd', // Picard = Picard
		'pcm', // Naijá = Naija
		'pdc', // Deitsch = Deitsch
		'pfl', // Pälzisch = Palzisch
		'pi', // पालि = Pali
		'pih', // Norfuk / Pitkern = Norfuk pitkern
		'pl', // Polski = Polski
		'pms', // Piemontèis = Piemonteis
		'pnb', // پنجابی = Panjabi
		'pnt', // Ποντιακά = Pontiaka
		'ppl', // Nawat = Nawat
		'ps', // پښتو = Paxto
		'pt', // Português = Portugues
		'pwn', // Pinayuanan = Pinayuanan
		'qu', // Runa Simi = Runa simi
		'rki', // ရခိုင် = Rahkuing
		'rm', // Rumantsch = Rumantsch
		'rmy', // Romani čhib = Romani chib
		'rn', // Ikirundi = Ikirundi
		'ro', // Română = Romana
		'roa-rup', // Armãneashti = Armaneashti
		'roa-tara', // Tarandíne = Tarandíne
		'rsk', // Руски = Ruski
		'ru', // Русский = Russkiy
		'rue', // Русиньскый = Rusinskyy
		'rw', // Ikinyarwanda = Ikinyarwanda
		'sa', // संस्कृतम् = Samskrta
		'sah', // Саха тыла = Sakha tyla
		'sat', // ᱥᱟᱱᱛᱟᱲᱤ = Santari
		'sc', // Sardu = Sardu
		'scn', // Sicilianu = Sicilianu
		'sco', // Scots = Scots
		'sd', // سنڌي = Sindhi
		'se', // Davvisámegiella = Davvisamegiella
		'sg', // Sängö = Sango
		'sh', // Srpskohrvatski / српскохрватски = Srpskohrvatski
		'shi', // Taclḥit = Taclhit
		'shy', // Tacawit = Tacawit
		'shn', // တႆး = Tai
		'si', // සිංහල = Simhala
		'syl', // ꠍꠤꠟꠐꠤ = Siloti
		'simple', // Simple English = Simple English
		'sk', // Slovenčina = Slovencina
		'skr', // سرائیکی = Saraiki
		'sl', // Slovenščina = Slovenscina
		'sm', // Gagana Samoa = Gagana samoa
		'smn', // Anarâškielâ = Anaraskiela
		'sn', // ChiShona = Chishona
		'so', // Soomaaliga = Soomaaliga
		'sq', // Shqip = Shqip
		'sr', // Српски / srpski = Srpski
		'srn', // Sranantongo = Sranantongo
		'ss', // SiSwati = Siswati
		'st', // Sesotho = Sesotho
		'stq', // Seeltersk = Seeltersk
		'su', // Sunda = Sunda
		'sv', // Svenska = Svenska
		'sw', // Kiswahili = Kiswahili
		'szy', // Sakizaya = Sakizaya
		'szl', // Ślůnski = Slunski
		'ta', // தமிழ் = Tamil
		'tay', // Tayal = Tayal
		'tcy', // ತುಳು = Tulu
		'tdd', // ᥖᥭᥰ ᥖᥬᥲ ᥑᥨᥒᥰ = Tai tau hong
		'te', // తెలుగు = Telugu
		'tet', // Tetun = Tetun
		'tg', // Тоҷикӣ = Tochiky
		'th', // ไทย = Tai
		'ti', // ትግርኛ = Tegrenna
		'ty', // Reo tahiti = Reo tahiti
		'tig', // ትግሬ = Tegre
		'tk', // Türkmençe = Turkmence
		'tl', // Tagalog = Tagalog
		'tly', // Tolışi = Tolisi
		'tn', // Setswana = Setswana
		'to', // Lea faka-Tonga = Lea faka tonga-
		'tok', // toki pona = Toki pona
		'tpi', // Tok Pisin = Tok pisin
		'tr', // Türkçe = Turkce
		'trv', // Seediq = Seediq
		'ts', // Xitsonga = Xitsonga
		'tt', // Татарча / tatarça = Tatarca
		'tum', // ChiTumbuka = Chitumbuka
		'tw', // Twi = Twi
		'tyv', // Тыва дыл = Tyva dyl
		'udm', // Удмурт = Udmurt
		'ug', // ئۇيغۇرچە / Uyghurche = Uyghurche
		'uk', // Українська = Ukrainska
		'ur', // اردو = Urdu
		'uz', // Oʻzbekcha / ўзбекча = Ozbekcha
		've', // Tshivenda = Tshivenda
		'vec', // Vèneto = Veneto
		'vep', // Vepsän kel’ = Vepsan kel
		'vi', // Tiếng Việt = Tieng viet
		'vls', // West-Vlams = West-vlams
		'vo', // Volapük = Volapuk
		'wa', // Walon = Walon
		'war', // Winaray = Winaray
		'wo', // Wolof = Wolof
		'wuu', // 吴语 = Wuyu
		'xal', // Хальмг = Khalmg
		'xh', // IsiXhosa = Isixhosa
		'xmf', // მარგალური = Margaluri
		'za', // Vahcuengh = Vahcuengh
		'zea', // Zeêuws = Zeeuws
		'zgh', // ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ = Tamazight tanawayt
		'zh', // 中文 = Zhongwen
		'zh-classical', // 文言 = Wenyan
		'zh-yue', // 粵語 = Yueyu
		'zh-min-nan', // 閩南語 / Bân-lâm-gí = Banlamgi
		'zu', // IsiZulu = Isizulu
	],
	// by first word, Roman letters first
	'alphabetic_svwiktionary' => [
		// Latin script
		'ace', // Acèh = Aceh
		'ang', // Ænglisc = Aenglisc
		'af', // Afrikaans = Afrikaans
		'ak', // Akan = Akan
		'als', // Alemannisch = Alemannisch
		'smn', // Anarâškielâ = Anaraskiela
		'ab', // Аԥсшәа = Apshea
		'an', // Aragonés = Aragones
		'roa-rup', // Armãneashti = Armaneashti
		'frp', // Arpetan = Arpetan
		'ast', // Asturianu = Asturianu
		'atj', // Atikamekw = Atikamekw
		'gn', // Avañe'ẽ = Avanee
		'av', // Авар = Avar
		'ay', // Aymar aru = Aymar aru
		'az', // Azərbaycanca = Azarbaycanca
		'gor', // Bahasa Hulontalo = Bahasa Hulontalo
		'id', // Bahasa Indonesia = Bahasa Indonesia
		'ms', // Bahasa Melayu = Bahasa Melayu
		'bdr', // Bajau Sama = Bajau sama
		'bm', // Bamanankan = Bamanankan
		'bjn', // Banjar = Banjar
		'map-bms', // Basa Banyumasan = Basa Banyumasan
		'ban', // Basa Bali = Basa Bali
		'bug', // Basa Ugi = Basa ugi
		'btm', // Batak Mandailing = Batak mandailing
		'bbc', // Batak Toba = Batak toba
		'bew', // Betawi = Betawi
		'bcl', // Bikol Central = Bikol central
		'bi', // Bislama = Bislama
		'bar', // Boarisch = Boarisch
		'bs', // Bosanski = Bosanski
		'br', // Brezhoneg = Brezhoneg
		'ca', // Català = Catala
		'ceb', // Cebuano = Cebuano
		'cs', // Čeština = Cestina
		'cho', // Chahta anumpa = Chahta anumpa
		'ch', // Chamoru = Chamoru
		'cbk-zam', // Chavacano de Zamboanga = Chavacano de Zamboanga
		'ny', // Chi-Chewa = Chichewa
		'sn', // ChiShona = Chishona
		'tum', // ChiTumbuka = Chitumbuka
		'co', // Corsu = Corsu
		'cy', // Cymraeg = Cymraeg
		'dga', // Dagaare = Dagaare
		'dag', // Dagbanli = Dagbanli
		'da', // Dansk = Dansk
		'se', // Davvisámegiella = Davvisamegiella
		'pdc', // Deitsch = Deitsch
		'de', // Deutsch = Deutsch
		'nv', // Diné bizaad = Dine bizaad
		'dsb', // Dolnoserbski = Dolnoserbski
		'na', // Dorerin Naoero = Dorerin naoero
		'mh', // Ebon = Ebon
		'et', // Eesti = Eesti
		'eml', // Emiliàn e rumagnòl = Emilian e rumagnol
		'en', // English = English
		'es', // Español = Espanol
		'eo', // Esperanto = Esperanto
		'ext', // Estremeñu = Estremenu
		'eu', // Euskara = Euskara
		'ee', // Eʋegbe = Evegbe
		'gur', // Farefare = Farefare
		'hif', // Fiji Hindi = Fiji Hindi
		'fon', // Fɔ̀ngbè = Fongbe
		'fo', // Føroyskt = Foroyskt
		'fr', // Français = Francais
		'fy', // Frysk = Frysk
		'ff', // Fulfulde = Fulfulde
		'fur', // Furlan = Furlan
		'ga', // Gaeilge = Gaeilge
		'gv', // Gaelg = Gaelg
		'sm', // Gagana Samoa = Gagana samoa
		'gag', // Gagauz = Gagauz
		'gd', // Gàidhlig = Gaidhlig
		'gl', // Galego = Galego
		'gpe', // Ghanaian Pidgin = Ghanaian Pidgin
		'ki', // Gĩkũyũ = Gikuyu
		'gom', // गोंयची कोंकणी / Gõychi Konknni = Goychi konknni
		'guw', // Gungbe = Gungbe
		'ha', // Hausa = Hausa
		'haw', // Hawaiʻi = Hawaii
		'ho', // Hiri Motu = Hiri motu
		'hsb', // Hornjoserbsce = Hornjoserbsce
		'hr', // Hrvatski = Hrvatski
		'io', // Ido = Ido
		'igl', // Igala = Igala
		'ig', // Igbo = Igbo
		'rw', // Ikinyarwanda = Ikinyarwanda
		'rn', // Ikirundi = Ikirundi
		'ilo', // Ilokano = Ilokano
		'ia', // Interlingua = Interlingua
		'ie', // Interlingue = Interlingue
		'iu', // ᐃᓄᒃᑎᑐᑦ / inuktitut = Inuktitut
		'ik', // Iñupiatun = Inupiatun
		'nr', // IsiNdebele seSewula = Isindbele sesewula
		'xh', // IsiXhosa = Isixhosa
		'zu', // IsiZulu = Isizulu
		'is', // Íslenska = Islenska
		'it', // Italiano = Italiano
		'iba', // Jaku Iban = Jaku Iban
		'jv', // Jawa = Jawa
		'kaj', // Jju = Jju
		'kbp', // Kabɩyɛ = Kabiye
		'dtp', // Kadazandusun = Kadazandusun
		'kl', // Kalaallisut = Kalaallisut
		'kr', // kanuri = Kanuri
		'pam', // Kapampangan = Kapampangan
		'krc', // Къарачай-малкъар = Karachaymalkar
		'csb', // Kaszëbsczi = Kaszebsczi
		'kw', // Kernowek = Kernowek
		'sw', // Kiswahili = Kiswahili
		'kg', // Kongo = Kongo
		'avk', // Kotava = Kotava
		'ht', // Kreyòl ayisyen = Kreyol ayisyen
		'gcr', // Kriyòl gwiyannen = Kriyol gwiyannen
		'kge', // Kumoring = Kumoring
		'ku', // Kurdî = Kurdi
		'kus', // Kʋsaal = Kusaal
		'kj', // Kwanyama = Kwanyama
		'lld', // Ladin = Ladin
		'lad', // Ladino = Ladino
		'jbo', // La .lojban = La lojban
		'ltg', // Latgaļu = Latgalu
		'la', // Latina = Latina
		'lv', // Latviešu = Latviesu
		'to', // Lea faka-Tonga = Lea faka tonga-
		'lb', // Lëtzebuergesch = Letzebuergesch
		'lt', // Lietuvių = Lietuviu
		'nia', // Li Niha = Li niha
		'lij', // Ligure = Ligure
		'li', // Limburgs = Limburgs
		'ln', // Lingála = Lingala
		'lfn', // Lingua Franca Nova = Lingua Franca Nova
		'olo', // Livvinkarjala = Livvinkarjala
		'lg', // Luganda = Luganda
		'lmo', // Lombard = Lombard
		'mad', // Madhurâ = Madhura
		'hu', // Magyar = Magyar
		'mk', // Македонски = Makedonski
		'mg', // Malagasy = Malagasy
		'mt', // Malti = Malti
		'mi', // Māori = Maori
		'fat', // Mfantse = Mfantse
		'min', // Minangkabau = Minangkabau
		'cdo', // 閩東語 / Mìng-dĕ̤ng-ngṳ̄ = Mingde ngngu
		'mwl', // Mirandés = Mirandes
		'mn', // Монгол = Mongol
		'mos', // Moore = Moore
		'mus', // Mvskoke = Mvskoke
		'nah', // Nāhuatl = Nahuatl
		'pcm', // Naijá = Naija
		'nap', // Napulitano = Napulitano
		'fj', // Na Vosa Vakaviti = Na vosa vakaviti
		'ppl', // Nawat = Nawat
		'nl', // Nederlands = Nederlands
		'nds-nl', // Nedersaksies = Nedersaksies
		'cr', // Nēhiyawēwin / ᓀᐦᐃᔭᐍᐏᐣ = Nehiyawewin
		'frr', // Nordfriisk = Nordfriisk
		'pih', // Norfuk / Pitkern = Norfuk pitkern
		'no', // Norsk = Norsk
		'nb', // Norsk bokmål = Norsk bokmal
		'nn', // Norsk nynorsk = Norsk nynorsk
		'nrm', // Nouormand = Nouormand
		'nov', // Novial = Novial
		'nup', // Nupe = Nupe
		'ann', // Obolo = Obolo
		'oc', // Occitan = Occitan
		'om', // Oromoo = Oromoo
		'ng', // Oshiwambo = Oshiwambo
		'hz', // Otsiherero = Otsiherero
		'uz', // Oʻzbekcha / ўзбекча = Ozbekcha
		'pfl', // Pälzisch = Palzisch
		'pag', // Pangasinan = Pangasinan
		'ami', // Pangcah = Pangcah
		'pap', // Papiamentu = Papiamentu
		'jam', // Patois = Patois
		'koi', // Перем коми = Perem komi
		'pcd', // Picard = Picard
		'pms', // Piemontèis = Piemonteis
		'pwn', // Pinayuanan = Pinayuanan
		'nds', // Plattdüütsch = Plattduutsch
		'pl', // Polski = Polski
		'tpi', // Tok Pisin = Tok pisin
		'tok', // toki pona = Toki pona
		'pt', // Português = Portugues
		'aa', // Qafár af = Qafar af
		'kaa', // Qaraqalpaqsha = Qaraqalpaqsha
		'crh', // Qırımtatarca = Qirimtatarca
		'ty', // Reo tahiti = Reo tahiti
		'ksh', // Ripoarisch = Ripoarisch
		'ro', // Română = Romana
		'rmy', // Romani čhib = Romani chib
		'rm', // Rumantsch = Rumantsch
		'qu', // Runa Simi = Runa simi
		'szy', // Sakizaya = Sakizaya
		'sg', // Sängö = Sango
		'sc', // Sardu = Sardu
		'sco', // Scots = Scots
		'trv', // Seediq = Seediq
		'stq', // Seeltersk = Seeltersk
		'st', // Sesotho = Sesotho
		'nso', // Sesotho sa Leboa = Sesotho sa leboa
		'tn', // Setswana = Setswana
		'sq', // Shqip = Shqip
		'scn', // Sicilianu = Sicilianu
		'simple', // Simple English = Simple English
		'ss', // SiSwati = Siswati
		'sk', // Slovenčina = Slovencina
		'sl', // Slovenščina = Slovenscina
		'szl', // Ślůnski = Slunski
		'so', // Soomaaliga = Soomaaliga
		'srn', // Sranantongo = Sranantongo
		'sr', // Српски / srpski = Srpski
		'sh', // Srpskohrvatski / српскохрватски = Srpskohrvatski
		'su', // Sunda = Sunda
		'fi', // Suomi = Suomi
		'sv', // Svenska = Svenska
		'shy', // Tacawit = Tacawit
		'shi', // Taclḥit = Taclhit
		'tl', // Tagalog = Tagalog
		'kab', // Taqbaylit = Taqbaylit
		'roa-tara', // Tarandíne = Tarandíne
		'tt', // Татарча / tatarça = Tatarca
		'tay', // Tayal = Tayal
		'tet', // Tetun = Tetun
		'din', // Thuɔŋjäŋ = Thuonjan
		'vi', // Tiếng Việt = Tieng viet
		'tly', // Tolışi = Tolisi
		'chy', // Tsetsêhestâhese = Tsetsehestahese
		've', // Tshivenda = Tshivenda
		'tr', // Türkçe = Turkce
		'tk', // Türkmençe = Turkmence
		'tw', // Twi = Twi
		'kcg', // Tyap = Tyap
		'ug', // ئۇيغۇرچە / Uyghurche = Uyghurche
		'za', // Vahcuengh = Vahcuengh
		'vec', // Vèneto = Veneto
		'vep', // Vepsän kel’ = Vepsan kel
		'vo', // Volapük = Volapuk
		'fiu-vro', // Võro = Voro
		'wa', // Walon = Walon
		'guc', // Wayuunaiki = Wayuunaiki
		'vls', // West-Vlams = West-vlams
		'war', // Winaray = Winaray
		'wo', // Wolof = Wolof
		'ts', // Xitsonga = Xitsonga
		'knc', // Yerwa Kanuri = Yerwa kanuri
		'yo', // Yorùbá = Yoruba
		'diq', // Zazaki = Zazaki
		'zea', // Zeêuws = Zeeuws
		'bat-smg', // Žemaitėška = Zemaiteska
		// Greek
		'el', // Ελληνικά = Ellinika
		'pnt', // Ποντιακά = Pontiaka
		'got', // 𐌲𐌿𐍄𐌹𐍃𐌺 = Gutisk
		// Cyrillic
		'ady', // Адыгабзэ = Adygabee
		'alt', // Алтай тил = Altay til
		'kbd', // Адыгэбзэ = Adygebee
		'ba', // Башҡортса = Bashkortsa
		'be', // Беларуская = Belaruskaya
		'be-x-old', // Беларуская (тарашкевіца) = Belaruskaya, tarashkevitsa
		'bxr', // Буряад = Budyaad
		'bg', // Български = Bugarski
		'ce', // Нохчийн = Nokhchiyn
		'cu', // Словѣньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ = Slovyansk
		'cv', // Чӑвашла = Chavashla
		'inh', // ГӀалгӀай = Ghalghaj
		'kk', // Қазақша = Qazaqsa
		'kv', // Коми = Komi
		'ky', // Кыргызча = Kyrgyzcha
		'lbe', // Лакку = Lakku
		'mdf', // Мокшень = Mokshen
		'mhr', // Олык марий = Olyk mariy
		'mo', // молдовеняскэ = Moldovenyaske
		'mrj', // Кырык мары = Kyryk mary
		'myv', // Эрзянь = Erzyan
		'os', // Ирон = Iron
		'rsk', // Руски = Ruski
		'ru', // Русский = Russkiy
		'rue', // Русиньскый = Rusinskyy
		'sah', // Саха тыла = Sakha tyla
		'tg', // Тоҷикӣ = Tochiky
		'tyv', // Тыва дыл = Tyva dyl
		'udm', // Удмурт = Udmurt
		'uk', // Українська = Ukrainska
		'xal', // Хальмг = Khalmg
		// Arabic
		'ar', // العربية = Alarabiyyah
		'ary', // الدارجة = Addarija
		'arz', // مصرى = Masri
		'azb', // تۆرکجه = Azarbaycan dili
		'ckb', // کوردی = Kurdi
		'fa', // فارسی = Farsi
		'glk', // گیلکی = Gilaki
		'ks', // کٲشُر = Kasur
		'lez', // Лезги = Lezgi
		'lrc', // لۊری شومالی = Luri
		'mzn', // مازِرونی = Mazeruni
		'pnb', // پنجابی = Panjabi
		'ps', // پښتو = Paxto
		'sd', // سنڌي = Sindhi
		'skr', // سرائیکی = Saraiki
		'ur', // اردو = Urdu
		'arc', // ܐܪܡܝܐ = Aramaya
		'dv', // ދިވެހިބަސް = Divehi
		// Hebrew
		'he', // עברית = Ivrit
		'yi', // ייִדיש = Yidish
		// Caucasian
		'hy', // Հայերեն = Hayeren
		'hyw', // Արեւմտահայերէն = Arevmdahayeren
		'ka', // ქართული = Kartuli
		'xmf', // მარგალური = Margaluri
		// Brahmic
		'anp', // अंगिका = Amgika
		'as', // অসমীয়া = Asamiya
		'awa', // अवधी = Avadhi
		'bh', // भोजपुरी = Bhojpur
		'blk', // ပအိုဝ်ႏဘာႏသာႏ = Paophasa
		'bn', // বাংলা = Bangla
		'bo', // བོད་ཡིག = Bod yig
		'bpy', // বিষ্ণুপ্রিয়া মণিপুরী = Bisnupriya monipuri
		'dty', // डोटेली = Dotyali
		'dz', // ཇོང་ཁ = Dzongkha
		'gu', // ગુજરાતી = Gujrat
		'hi', // हिन्दी = Hindi
		'km', // ភាសាខ្មែរ = Khmae
		'kn', // ಕನ್ನಡ = Kannada
		'lo', // ລາວ = Lao
		'mai', // मैथिली = Maithili
		'ml', // മലയാളം = Malayalam
		'mni', // ꯃꯤꯇꯩ ꯂꯣꯟ = Meitei
		'mnw', // ဘာသာမန် = Bhasa mon
		'mr', // मराठी = Marathi
		'my', // မြန်မာဘာသာ = Mranma
		'ne', // नेपाली = Nepali
		'new', // नेपाल भाषा = Nepala bhasa
		'or', // ଓଡ଼ିଆ = Oria
		'pa', // ਪੰਜਾਬੀ = Panjabi
		'pi', // पालि = Pali
		'rki', // ရခိုင် = Rahkuing
		'sa', // संस्कृतम् = Samskrta
		'sat', // ᱥᱟᱱᱛᱟᱲᱤ = Santari
		'shn', // တႆး = Tai
		'si', // සිංහල = Simhala
		'syl', // ꠍꠤꠟꠐꠤ = Siloti
		'ta', // தமிழ் = Tamil
		'tcy', // ತುಳು = Tulu
		'tdd', // ᥖᥭᥰ ᥖᥬᥲ ᥑᥨᥒᥰ = Tai tau hong
		'te', // తెలుగు = Telugu
		'th', // ไทย = Tai
		// African
		'am', // አማርኛ = Amarenna
		'tig', // ትግሬ = Tegre
		'ti', // ትግርኛ = Tegrenna
		'nqo', // ߒߞߏ = Nko
		'zgh', // ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ = Tamazight tanawayt
		// CJK
		'gan', // 贛語 = Ganyu
		'hak', // 客家語 / Hak-kâ-ngî = Hakkangi
		'ii', // ꆇꉙ = Nuosuhxop
		'ja', // 日本語 = Nihongo
		'ko', // 한국어 = Hangugeo
		'nan', // 閩南語 / Bân-lâm-gí = Banlamgi
		'wuu', // 吴语 = Wuyu
		'yue', // 粵語 = Yueyu
		'zh', // 中文 = Zhongwen
		'zh-classical', // 文言 = Wenyan
		'zh-min-nan', // 閩南語 / Bân-lâm-gí = Banlamgi
		'zh-yue', // 粵語 = Yueyu
		// Other
		'chr', // ᏣᎳᎩ = Tsalagi
	],
];
