swagger: '2.0'
info:
  version: 1.31.0
  title: MediaWiki
  description: The Wiki software solution used on Wikipedia and its sister projects
  termsOfService: https://foundation.wikimedia.org/wiki/Terms_of_Use
paths:
  /wiki/{title}:
    get:
      x-amples:
        - title: Main Page
          request:
            params:
              title: Main_Page
          response:
            status: 200
            headers:
              content-type: /text\/html/
            body: /"wgPageName":"Main_Page"/
        - title: Special Version
          request:
            params:
              title: Special:Version
          response:
            status: 200
            headers:
              content-type: /text\/html/
            body: /WITHOUT ANY WARRANTY/
  /w/api.php:
    post:
      x-amples:
        - title: Main Page pageprops
          request:
            body:
              action: query
              prop: pageprops
              titles: Main_Page
              format: json
              formatversion: 2
            headers:
              accept: application/json
          response:
            status: 200
            headers:
              content-type: /application\/json/
            body: /.+/
